// 雅思词库 Part 4 - 听力高频词汇（国家、健康、住房、语言、市场营销、材料）
var vocabularyPart4 = [
    // ===== 国家 Countries =====
    { word: "brazil", phonetic: "/brəˈzɪl/", meaning: "巴西", category: "countries", distractors: ["阿根廷", "智利", "秘鲁"] },
    { word: "china", phonetic: "/ˈtʃaɪnə/", meaning: "中国", category: "countries", distractors: ["日本", "韩国", "越南"] },
    { word: "egypt", phonetic: "/ˈiːdʒɪpt/", meaning: "埃及", category: "countries", distractors: ["摩洛哥", "南非", "肯尼亚"] },
    { word: "england", phonetic: "/ˈɪŋɡlənd/", meaning: "英格兰", category: "countries", distractors: ["苏格兰", "威尔士", "爱尔兰"] },
    { word: "france", phonetic: "/frɑːns/", meaning: "法国", category: "countries", distractors: ["德国", "意大利", "西班牙"] },
    { word: "germany", phonetic: "/ˈdʒɜːməni/", meaning: "德国", category: "countries", distractors: ["法国", "荷兰", "比利时"] },
    { word: "greece", phonetic: "/ɡriːs/", meaning: "希腊", category: "countries", distractors: ["土耳其", "意大利", "埃及"] },
    { word: "india", phonetic: "/ˈɪndiə/", meaning: "印度", category: "countries", distractors: ["巴基斯坦", "孟加拉", "尼泊尔"] },
    { word: "indonesia", phonetic: "/ˌɪndəˈniːziə/", meaning: "印度尼西亚", category: "countries", distractors: ["马来西亚", "菲律宾", "泰国"] },
    { word: "italy", phonetic: "/ˈɪtəli/", meaning: "意大利", category: "countries", distractors: ["法国", "西班牙", "希腊"] },
    { word: "malaysia", phonetic: "/məˈleɪziə/", meaning: "马来西亚", category: "countries", distractors: ["新加坡", "泰国", "印尼"] },
    { word: "mexico", phonetic: "/ˈmeksɪkəʊ/", meaning: "墨西哥", category: "countries", distractors: ["美国", "加拿大", "古巴"] },
    { word: "singapore", phonetic: "/ˌsɪŋəˈpɔːr/", meaning: "新加坡", category: "countries", distractors: ["马来西亚", "泰国", "菲律宾"] },
    { word: "switzerland", phonetic: "/ˈswɪtsələnd/", meaning: "瑞士", category: "countries", distractors: ["奥地利", "德国", "法国"] },
    { word: "turkey", phonetic: "/ˈtɜːki/", meaning: "土耳其", category: "countries", distractors: ["希腊", "伊朗", "伊拉克"] },

    // ===== 健康食品 Health Foods =====
    { word: "carbohydrates", phonetic: "/ˌkɑːbəʊˈhaɪdreɪts/", meaning: "碳水化合物", category: "health_foods", distractors: ["蛋白质", "脂肪", "维生素"] },
    { word: "cereals", phonetic: "/ˈsɪəriəlz/", meaning: "谷物", category: "health_foods", distractors: ["水果", "蔬菜", "肉类"] },
    { word: "protein", phonetic: "/ˈprəʊtiːn/", meaning: "蛋白质", category: "health_foods", distractors: ["碳水化合物", "脂肪", "糖分"] },
    { word: "vitamin", phonetic: "/ˈvɪtəmɪn/", meaning: "维生素", category: "health_foods", distractors: ["矿物质", "纤维", "糖分"] },
    { word: "minerals", phonetic: "/ˈmɪnərəlz/", meaning: "矿物质", category: "health_foods", distractors: ["维生素", "蛋白质", "脂肪"] },
    { word: "vegetarian", phonetic: "/ˌvedʒəˈteəriən/", meaning: "素食者", category: "health_foods", distractors: ["肉食者", "杂食者", "无食者"] },
    { word: "balanced diet", phonetic: "/ˌbælənst ˈdaɪət/", meaning: "均衡饮食", category: "health_foods", distractors: ["偏食", "暴食", "节食"] },
    { word: "seafood", phonetic: "/ˈsiːfuːd/", meaning: "海鲜", category: "health_foods", distractors: ["红肉", "禽肉", "野味"] },
    { word: "remedy", phonetic: "/ˈremədi/", meaning: "治疗", category: "health_foods", distractors: ["疾病", "症状", "问题"] },
    { word: "medicine", phonetic: "/ˈmedsn/", meaning: "药物", category: "health_foods", distractors: ["毒药", "病毒", "细菌"] },
    { word: "yoga", phonetic: "/ˈjəʊɡə/", meaning: "瑜伽", category: "health_foods", distractors: ["跑步", "游泳", "骑行"] },

    // ===== 住房 Homes =====
    { word: "basement", phonetic: "/ˈbeɪsmənt/", meaning: "地下室", category: "homes", distractors: ["阁楼", "屋顶", "阳台"] },
    { word: "bedroom", phonetic: "/ˈbedruːm/", meaning: "卧室", category: "homes", distractors: ["客厅", "厨房", "浴室"] },
    { word: "bungalow", phonetic: "/ˈbʌŋɡələʊ/", meaning: "平房", category: "homes", distractors: ["公寓", "别墅", "楼房"] },
    { word: "chimney", phonetic: "/ˈtʃɪmni/", meaning: "烟囱", category: "homes", distractors: ["窗户", "门", "墙壁"] },
    { word: "dormitory", phonetic: "/ˈdɔːmətri/", meaning: "宿舍", category: "homes", distractors: ["公寓", "别墅", "平房"] },
    { word: "duplex", phonetic: "/ˈdjuːpleks/", meaning: "复式公寓", category: "homes", distractors: ["单层公寓", "联排别墅", "独栋别墅"] },
    { word: "garden", phonetic: "/ˈɡɑːdn/", meaning: "花园", category: "homes", distractors: ["车库", "地下室", "阁楼"] },
    { word: "hallway", phonetic: "/ˈhɔːlweɪ/", meaning: "走廊", category: "homes", distractors: ["房间", "阳台", "车库"] },
    { word: "kitchen", phonetic: "/ˈkɪtʃɪn/", meaning: "厨房", category: "homes", distractors: ["卧室", "客厅", "浴室"] },
    { word: "landlord", phonetic: "/ˈlændlɔːd/", meaning: "房东", category: "homes", distractors: ["租户", "邻居", "访客"] },
    { word: "lease", phonetic: "/liːs/", meaning: "租约", category: "homes", distractors: ["购买", "销售", "赠送"] },
    { word: "microwave", phonetic: "/ˈmaɪkrəweɪv/", meaning: "微波炉", category: "homes", distractors: ["烤箱", "冰箱", "洗碗机"] },
    { word: "oven", phonetic: "/ˈʌvn/", meaning: "烤箱", category: "homes", distractors: ["微波炉", "冰箱", "洗衣机"] },
    { word: "refrigerator", phonetic: "/rɪˈfrɪdʒəreɪtər/", meaning: "冰箱", category: "homes", distractors: ["烤箱", "微波炉", "洗碗机"] },
    { word: "rent", phonetic: "/rent/", meaning: "租金", category: "homes", distractors: ["购买价", "押金", "服务费"] },
    { word: "sofa", phonetic: "/ˈsəʊfə/", meaning: "沙发", category: "homes", distractors: ["椅子", "床", "桌子"] },
    { word: "tenant", phonetic: "/ˈtenənt/", meaning: "租户", category: "homes", distractors: ["房东", "业主", "邻居"] },

    // ===== 语言 Languages =====
    { word: "bilingual", phonetic: "/baɪˈlɪŋɡwəl/", meaning: "双语的", category: "languages", distractors: ["单语的", "多语的", "无语的"] },
    { word: "linguistics", phonetic: "/lɪŋˈɡwɪstɪks/", meaning: "语言学", category: "languages", distractors: ["文学", "历史", "哲学"] },
    { word: "mandarin", phonetic: "/ˈmændərɪn/", meaning: "普通话", category: "languages", distractors: ["粤语", "闽南语", "客家话"] },
    { word: "polyglot", phonetic: "/ˈpɒliɡlɒt/", meaning: "通晓多国语言的人", category: "languages", distractors: ["单语者", "初学者", "文盲"] },
    { word: "trilingual", phonetic: "/traɪˈlɪŋɡwəl/", meaning: "三语的", category: "languages", distractors: ["双语的", "单语的", "多语的"] },

    // ===== 市场营销 Marketing =====
    { word: "catalogue", phonetic: "/ˈkætəlɒɡ/", meaning: "目录", category: "marketing", distractors: ["广告", "海报", "传单"] },
    { word: "competition", phonetic: "/ˌkɒmpəˈtɪʃn/", meaning: "竞争", category: "marketing", distractors: ["合作", "联盟", "伙伴"] },
    { word: "customer", phonetic: "/ˈkʌstəmər/", meaning: "顾客", category: "marketing", distractors: ["供应商", "制造商", "经销商"] },
    { word: "display", phonetic: "/dɪˈspleɪ/", meaning: "展示", category: "marketing", distractors: ["隐藏", "储存", "包装"] },
    { word: "interview", phonetic: "/ˈɪntəvjuː/", meaning: "面试", category: "marketing", distractors: ["考试", "培训", "实习"] },
    { word: "management", phonetic: "/ˈmænɪdʒmənt/", meaning: "管理", category: "marketing", distractors: ["执行", "操作", "生产"] },
    { word: "manufacture", phonetic: "/ˌmænjuˈfæktʃər/", meaning: "制造", category: "marketing", distractors: ["销售", "购买", "消费"] },
    { word: "merchandise", phonetic: "/ˈmɜːtʃəndaɪz/", meaning: "商品", category: "marketing", distractors: ["服务", "体验", "咨询"] },
    { word: "newsletter", phonetic: "/ˈnjuːzletər/", meaning: "通讯", category: "marketing", distractors: ["报纸", "杂志", "书籍"] },
    { word: "poll", phonetic: "/pəʊl/", meaning: "民意调查", category: "marketing", distractors: ["选举", "投票", "公决"] },
    { word: "products", phonetic: "/ˈprɒdʌkts/", meaning: "产品", category: "marketing", distractors: ["服务", "体验", "理念"] },
    { word: "questionnaire", phonetic: "/ˌkwestʃəˈneər/", meaning: "问卷", category: "marketing", distractors: ["答案", "报告", "分析"] },
    { word: "recruitment", phonetic: "/rɪˈkruːtmənt/", meaning: "招聘", category: "marketing", distractors: ["解雇", "辞退", "裁员"] },
    { word: "statistic", phonetic: "/stəˈtɪstɪk/", meaning: "统计数据", category: "marketing", distractors: ["猜测", "估计", "假设"] },
    { word: "strategies", phonetic: "/ˈstrætədʒiz/", meaning: "策略", category: "marketing", distractors: ["战术", "方法", "手段"] },
    { word: "survey", phonetic: "/ˈsɜːveɪ/", meaning: "调查", category: "marketing", distractors: ["猜测", "假设", "推断"] },
    { word: "trainee", phonetic: "/ˌtreɪˈniː/", meaning: "实习生", category: "marketing", distractors: ["培训师", "经理", "主管"] },
    { word: "training", phonetic: "/ˈtreɪnɪŋ/", meaning: "培训", category: "marketing", distractors: ["工作", "休息", "娱乐"] },

    // ===== 材料 Materials =====
    { word: "aluminum", phonetic: "/əˈluːmɪnəm/", meaning: "铝", category: "materials", distractors: ["铁", "铜", "钢"] },
    { word: "cement", phonetic: "/sɪˈment/", meaning: "水泥", category: "materials", distractors: ["沙子", "砖块", "木材"] },
    { word: "ceramics", phonetic: "/səˈræmɪks/", meaning: "陶瓷", category: "materials", distractors: ["玻璃", "塑料", "金属"] },
    { word: "concrete", phonetic: "/ˈkɒŋkriːt/", meaning: "混凝土", category: "materials", distractors: ["木材", "钢铁", "玻璃"] },
    { word: "copper", phonetic: "/ˈkɒpər/", meaning: "铜", category: "materials", distractors: ["铁", "铝", "锌"] },
    { word: "cotton", phonetic: "/ˈkɒtn/", meaning: "棉花", category: "materials", distractors: ["丝绸", "羊毛", "麻布"] },
    { word: "fabric", phonetic: "/ˈfæbrɪk/", meaning: "织物", category: "materials", distractors: ["皮革", "金属", "塑料"] },
    { word: "fiberglass", phonetic: "/ˈfaɪbəɡlɑːs/", meaning: "玻璃纤维", category: "materials", distractors: ["碳纤维", "塑料", "金属"] },
    { word: "fur", phonetic: "/fɜːr/", meaning: "皮毛", category: "materials", distractors: ["羽毛", "鳞片", "皮肤"] },
    { word: "glass", phonetic: "/ɡlɑːs/", meaning: "玻璃", category: "materials", distractors: ["塑料", "金属", "木材"] },
    { word: "glue", phonetic: "/ɡluː/", meaning: "胶水", category: "materials", distractors: ["螺丝", "钉子", "绳子"] },
    { word: "gold", phonetic: "/ɡəʊld/", meaning: "金", category: "materials", distractors: ["银", "铜", "铁"] },
    { word: "leather", phonetic: "/ˈleðər/", meaning: "皮革", category: "materials", distractors: ["织物", "塑料", "橡胶"] },
    { word: "lumber", phonetic: "/ˈlʌmbər/", meaning: "木材", category: "materials", distractors: ["钢材", "砖块", "水泥"] },
    { word: "metal", phonetic: "/ˈmetl/", meaning: "金属", category: "materials", distractors: ["塑料", "木材", "玻璃"] },
    { word: "paper", phonetic: "/ˈpeɪpər/", meaning: "纸", category: "materials", distractors: ["布料", "塑料", "金属"] },
    { word: "plastic", phonetic: "/ˈplæstɪk/", meaning: "塑料", category: "materials", distractors: ["金属", "玻璃", "木材"] },
    { word: "rubber", phonetic: "/ˈrʌbər/", meaning: "橡胶", category: "materials", distractors: ["塑料", "皮革", "织物"] },
    { word: "silver", phonetic: "/ˈsɪlvər/", meaning: "银", category: "materials", distractors: ["金", "铜", "铁"] },
    { word: "steel", phonetic: "/stiːl/", meaning: "钢", category: "materials", distractors: ["铁", "铝", "铜"] },
    { word: "stone", phonetic: "/stəʊn/", meaning: "石头", category: "materials", distractors: ["砖块", "水泥", "木材"] },
    { word: "textile", phonetic: "/ˈtekstaɪl/", meaning: "纺织品", category: "materials", distractors: ["皮革", "金属", "塑料"] },
    { word: "wax", phonetic: "/wæks/", meaning: "蜡", category: "materials", distractors: ["油", "脂", "树脂"] },
    { word: "wood", phonetic: "/wʊd/", meaning: "木头", category: "materials", distractors: ["金属", "塑料", "玻璃"] },
    { word: "wool", phonetic: "/wʊl/", meaning: "羊毛", category: "materials", distractors: ["棉花", "丝绸", "麻布"] },

    // ===== 职业 Occupations =====
    { word: "accountant", phonetic: "/əˈkaʊntənt/", meaning: "会计师", category: "occupations", distractors: ["律师", "医生", "工程师"] },
    { word: "architect", phonetic: "/ˈɑːkɪtekt/", meaning: "建筑师", category: "occupations", distractors: ["工程师", "设计师", "画家"] },
    { word: "captain", phonetic: "/ˈkæptɪn/", meaning: "船长", category: "occupations", distractors: ["水手", "乘客", "游客"] },
    { word: "cashier", phonetic: "/kæˈʃɪər/", meaning: "收银员", category: "occupations", distractors: ["经理", "店员", "保安"] },
    { word: "clerk", phonetic: "/klɑːk/", meaning: "职员", category: "occupations", distractors: ["经理", "主管", "老板"] },
    { word: "craftsman", phonetic: "/ˈkrɑːftsmən/", meaning: "工匠", category: "occupations", distractors: ["工人", "经理", "销售员"] },
    { word: "decorator", phonetic: "/ˈdekəreɪtər/", meaning: "装饰师", category: "occupations", distractors: ["建筑师", "设计师", "画家"] },
    { word: "designer", phonetic: "/dɪˈzaɪnər/", meaning: "设计师", category: "occupations", distractors: ["工程师", "建筑师", "画家"] },
    { word: "engineer", phonetic: "/ˌendʒɪˈnɪər/", meaning: "工程师", category: "occupations", distractors: ["科学家", "技术员", "操作员"] },
    { word: "freelance", phonetic: "/ˈfriːlɑːns/", meaning: "自由职业者", category: "occupations", distractors: ["雇员", "全职员工", "合同工"] },
    { word: "guard", phonetic: "/ɡɑːd/", meaning: "保安", category: "occupations", distractors: ["经理", "店员", "顾客"] },
    { word: "lecturer", phonetic: "/ˈlektʃərər/", meaning: "讲师", category: "occupations", distractors: ["学生", "助教", "院长"] },
    { word: "manager", phonetic: "/ˈmænɪdʒər/", meaning: "经理", category: "occupations", distractors: ["员工", "实习生", "临时工"] },
    { word: "pilot", phonetic: "/ˈpaɪlət/", meaning: "飞行员", category: "occupations", distractors: ["空乘", "乘客", "调度员"] },
    { word: "professor", phonetic: "/prəˈfesər/", meaning: "教授", category: "occupations", distractors: ["学生", "助教", "讲师"] },
    { word: "psychologist", phonetic: "/saɪˈkɒlədʒɪst/", meaning: "心理学家", category: "occupations", distractors: ["医生", "护士", "治疗师"] },
    { word: "receptionist", phonetic: "/rɪˈsepʃənɪst/", meaning: "接待员", category: "occupations", distractors: ["经理", "秘书", "助理"] },
    { word: "secretary", phonetic: "/ˈsekrətri/", meaning: "秘书", category: "occupations", distractors: ["经理", "助理", "接待员"] },
    { word: "specialist", phonetic: "/ˈspeʃəlɪst/", meaning: "专家", category: "occupations", distractors: ["普通员工", "实习生", "助手"] },
    { word: "teacher", phonetic: "/ˈtiːtʃər/", meaning: "教师", category: "occupations", distractors: ["学生", "家长", "校长"] },
    { word: "volunteer", phonetic: "/ˌvɒlənˈtɪər/", meaning: "志愿者", category: "occupations", distractors: ["员工", "雇员", "承包商"] },
    { word: "waiter", phonetic: "/ˈweɪtər/", meaning: "服务员", category: "occupations", distractors: ["厨师", "经理", "顾客"] },
    { word: "waitress", phonetic: "/ˈweɪtrəs/", meaning: "女服务员", category: "occupations", distractors: ["厨师", "经理", "顾客"] }
];
