// 雅思词库 Part 20 - 通用高频词汇补全 W-Z 及其他
var vocabularyPart20 = [
    { word: "warfare", phonetic: "/ˈwɔːfeə/", meaning: "战争", category: "general", distractors: ["和平", "友谊", "外交"] },
    { word: "warranty", phonetic: "/ˈwɒrənti/", meaning: "保修", category: "general", distractors: ["损坏", "丢弃", "使用"] },
    { word: "water-soluble", phonetic: "/ˈwɔːtə sɒljəbl/", meaning: "水溶性的", category: "general", distractors: ["脂溶性的", "难溶的", "固态的"] },
    { word: "wavelength", phonetic: "/ˈweɪvleŋθ/", meaning: "波长", category: "general", distractors: ["频率", "振幅", "速度"] },
    { word: "wealthy", phonetic: "/ˈwelθi/", meaning: "富有的", category: "general", distractors: ["贫穷的", "吝啬的", "普通的"] },
    { word: "weapon", phonetic: "/ˈwepən/", meaning: "武器", category: "general", distractors: ["防具", "工具", "玩具"] },
    { word: "weary", phonetic: "/ˈwɪəri/", meaning: "疲倦的", category: "general", distractors: ["兴奋的", "强壮的", "好奇的"] },
    { word: "weed", phonetic: "/wiːd/", meaning: "杂草", category: "general", distractors: ["花朵", "庄稼", "树木"] },
    { word: "welfare", phonetic: "/ˈwelfeə/", meaning: "福利", category: "general", distractors: ["伤害", "剥削", "惩罚"] },
    { word: "whereas", phonetic: "/ˌweərˈæz/", meaning: "然而", category: "general", distractors: ["此外", "相同", "因此"] },
    { word: "whereby", phonetic: "/weəˈbaɪ/", meaning: "凭此", category: "general", distractors: ["然而", "但是", "除非"] },
    { word: "whilst", phonetic: "/waɪlst/", meaning: "在...期间", category: "general", distractors: ["之后", "之前", "后来"] },
    { word: "wholesale", phonetic: "/ˈhəʊlseɪl/", meaning: "批发", category: "general", distractors: ["零售", "赠送", "遗失"] },
    { word: "widespread", phonetic: "/ˈwaɪdspred/", meaning: "广泛的", category: "general", distractors: ["局部的", "罕见的", "隐蔽的"] },
    { word: "wildlife", phonetic: "/ˈwaɪldlaɪf/", meaning: "野生动物", category: "general", distractors: ["家畜", "宠物", "人类"] },
    { word: "willingness", phonetic: "/ˈwɪlɪŋnəs/", meaning: "自愿", category: "general", distractors: ["被迫", "反抗", "迟疑"] },
    { word: "wisdom", phonetic: "/ˈwɪzdəm/", meaning: "智慧", category: "general", distractors: ["愚蠢", "无知", "本能"] },
    { word: "withdraw", phonetic: "/wɪðˈdrɔː/", meaning: "撤回；取款", category: "general", distractors: ["存入", "推进", "坚持"] },
    { word: "witness", phonetic: "/ˈwɪtnəs/", meaning: "见证人", category: "general", distractors: ["参与者", "罪犯", "警察"] },
    { word: "worldwide", phonetic: "/ˌwɜːldˈwaɪd/", meaning: "全世界的", category: "general", distractors: ["当地的", "区域的", "内陆的"] },
    { word: "worthwhile", phonetic: "/ˌwɜːθˈwaɪl/", meaning: "值得做的", category: "general", distractors: ["徒劳的", "琐碎的", "有害的"] },
    { word: "wounded", phonetic: "/ˈwuːndɪd/", meaning: "受伤的", category: "general", distractors: ["健康的", "强壮的", "安全的"] },
    { word: "wrap", phonetic: "/ræp/", meaning: "包裹", category: "general", distractors: ["拆开", "丢弃", "展示"] },
    { word: "wrinkle", phonetic: "/ˈrɪŋkl/", meaning: "皱纹", category: "general", distractors: ["光滑", "伤疤", "胎记"] },
    { word: "yield", phonetic: "/jiːld/", meaning: "产量；屈服", category: "general", distractors: ["投入", "反抗", "损失"] },
    { word: "zeal", phonetic: "/ziːl/", meaning: "热心", category: "general", distractors: ["冷漠", "厌恶", "懒散"] },
    { word: "zero", phonetic: "/ˈzɪərəʊ/", meaning: "零", category: "general", distractors: ["一", "百", "负数"] },
    { word: "zone", phonetic: "/zəʊn/", meaning: "区域", category: "general", distractors: ["中心", "全部", "点"] },
    // 补充听力/口语常用词
    { word: "affordable", phonetic: "/əˈfɔːdəbl/", meaning: "廉价的", category: "listening", distractors: ["贵的", "奢侈的", "唯一的"] },
    { word: "ancient", phonetic: "/ˈeɪnʃənt/", meaning: "古老的", category: "listening", distractors: ["现代的", "新奇的", "未来的"] },
    { word: "comfortable", phonetic: "/ˈkʌmftəbl/", meaning: "舒服的", category: "listening", distractors: ["难受的", "紧凑的", "寒冷的"] },
    { word: "convenient", phonetic: "/kənˈviːniənt/", meaning: "便利的", category: "listening", distractors: ["麻烦的", "遥远的", "琐碎的"] },
    { word: "dull", phonetic: "/dʌl/", meaning: "迟钝的；乏味的", category: "listening", distractors: ["有趣的", "锋利的", "兴奋的"] },
    { word: "energetic", phonetic: "/ˌenəˈdʒetɪk/", meaning: "精力充沛的", category: "listening", distractors: ["疲倦的", "懒惰的", "生病的"] },
    { word: "exciting", phonetic: "/ɪkˈsaɪtɪŋ/", meaning: "令人兴奋的", category: "listening", distractors: ["无聊的", "恐怖的", "悲伤的"] },
    { word: "extinct", phonetic: "/ɪkˈstɪŋkt/", meaning: "灭绝的", category: "listening", distractors: ["繁盛的", "活着的", "常见的"] },
    { word: "flexible", phonetic: "/ˈfleksəbl/", meaning: "灵活的", category: "listening", distractors: ["僵硬的", "固化的", "脆的"] },
    { word: "immense", phonetic: "/ɪˈmens/", meaning: "巨大的", category: "listening", distractors: ["小的", "极其微小的", "平凡的"] },
    { word: "knowledgeable", phonetic: "/ˈnɒlɪdʒəbl/", meaning: "博学的", category: "listening", distractors: ["愚蠢的", "无知的", "浅薄的"] },
    { word: "necessary", phonetic: "/ˈnesəsəri/", meaning: "必要的", category: "listening", distractors: ["多余的", "可选的", "琐碎的"] },
    { word: "optimistic", phonetic: "/ˌɒptɪˈmɪstɪk/", meaning: "乐观的", category: "listening", distractors: ["悲观的", "抑郁的", "现实的"] },
    { word: "pessimistic", phonetic: "/ˌpesɪˈmɪstɪk/", meaning: "悲观的", category: "listening", distractors: ["乐观的", "自信的", "活泼的"] },
    { word: "practical", phonetic: "/ˈpræktɪkl/", meaning: "实际的", category: "listening", distractors: ["虚幻的", "理论的", "理想的"] },
    { word: "realistic", phonetic: "/ˌrɪəˈlɪstɪk/", meaning: "现实的", category: "listening", distractors: ["空想的", "由于", "过去的"] },
    { word: "social", phonetic: "/ˈsəʊʃl/", meaning: "社会的", category: "listening", distractors: ["个人的", "私密的", "自闭的"] },
    { word: "suitable", phonetic: "/ˈsjuːtəbl/", meaning: "合适的", category: "listening", distractors: ["不合身的", "错误的", "麻烦的"] },
    { word: "tranquil", phonetic: "/ˈtræŋkwɪl/", meaning: "安静的", category: "listening", distractors: ["吵闹的", "繁忙的", "兴奋的"] },
    { word: "various", phonetic: "/ˈveəriəs/", meaning: "各种各样的", category: "listening", distractors: ["单一的", "同样的", "唯一的"] },
    { word: "vast", phonetic: "/vɑːst/", meaning: "辽阔的", category: "listening", distractors: ["狭小的", "拥挤的", "局限的"] },
    { word: "voluntary", phonetic: "/ˈvɒləntri/", meaning: "自愿的", category: "listening", distractors: ["强制的", "被迫的", "随机的"] }
];
