// 雅思词库 Part 3 - 话题词汇后半部分 + 听力高频词汇
var vocabularyPart3 = [
    // ===== 犯罪 Crime =====
    { word: "bystander", phonetic: "/ˈbaɪstændər/", meaning: "旁观者", category: "crime", distractors: ["参与者", "当事人", "责任人"] },
    { word: "commit", phonetic: "/kəˈmɪt/", meaning: "犯罪", category: "crime", distractors: ["阻止", "防止", "预防"] },
    { word: "consequence", phonetic: "/ˈkɒnsɪkwəns/", meaning: "后果", category: "crime", distractors: ["原因", "起因", "理由"] },
    { word: "deter", phonetic: "/dɪˈtɜːr/", meaning: "阻止，威慑", category: "crime", distractors: ["鼓励", "促进", "支持"] },
    { word: "enforce", phonetic: "/ɪnˈfɔːs/", meaning: "执行，强制", category: "crime", distractors: ["忽视", "放弃", "违反"] },
    { word: "harsh", phonetic: "/hɑːʃ/", meaning: "严厉的", category: "crime", distractors: ["温和的", "宽松的", "仁慈的"] },
    { word: "imprison", phonetic: "/ɪmˈprɪzn/", meaning: "监禁", category: "crime", distractors: ["释放", "自由", "赦免"] },
    { word: "juvenile", phonetic: "/ˈdʒuːvənaɪl/", meaning: "青少年的", category: "crime", distractors: ["成年的", "老年的", "儿童的"] },
    { word: "legalise", phonetic: "/ˈliːɡəlaɪz/", meaning: "使合法化", category: "crime", distractors: ["禁止", "违法", "取缔"] },
    { word: "lenient", phonetic: "/ˈliːniənt/", meaning: "宽大的", category: "crime", distractors: ["严厉的", "苛刻的", "严格的"] },
    { word: "offence", phonetic: "/əˈfens/", meaning: "犯罪，冒犯", category: "crime", distractors: ["善行", "好事", "帮助"] },
    { word: "petty", phonetic: "/ˈpeti/", meaning: "轻微的", category: "crime", distractors: ["严重的", "重大的", "恶劣的"] },
    { word: "predominantly", phonetic: "/prɪˈdɒmɪnəntli/", meaning: "主要地", category: "crime", distractors: ["次要地", "偶尔地", "少量地"] },
    { word: "prevent", phonetic: "/prɪˈvent/", meaning: "预防", category: "crime", distractors: ["允许", "促进", "鼓励"] },
    { word: "prohibit", phonetic: "/prəˈhɪbɪt/", meaning: "禁止", category: "crime", distractors: ["允许", "许可", "批准"] },
    { word: "prosecute", phonetic: "/ˈprɒsɪkjuːt/", meaning: "起诉", category: "crime", distractors: ["辩护", "无罪", "释放"] },
    { word: "punish", phonetic: "/ˈpʌnɪʃ/", meaning: "惩罚", category: "crime", distractors: ["奖励", "表扬", "鼓励"] },
    { word: "vandalism", phonetic: "/ˈvændəlɪzəm/", meaning: "故意破坏", category: "crime", distractors: ["保护", "修复", "维护"] },
    { word: "weapon", phonetic: "/ˈwepən/", meaning: "武器", category: "crime", distractors: ["工具", "玩具", "装饰"] },
    { word: "wrongdoing", phonetic: "/ˈrɒŋduːɪŋ/", meaning: "不法行为", category: "crime", distractors: ["善行", "正义", "美德"] },

    // ===== 媒体 Media =====
    { word: "biased", phonetic: "/ˈbaɪəst/", meaning: "有偏见的", category: "media", distractors: ["公正的", "客观的", "中立的"] },
    { word: "censor", phonetic: "/ˈsensər/", meaning: "审查", category: "media", distractors: ["公开", "发布", "传播"] },
    { word: "conflict", phonetic: "/ˈkɒnflɪkt/", meaning: "冲突", category: "media", distractors: ["和谐", "一致", "合作"] },
    { word: "controversial", phonetic: "/ˌkɒntrəˈvɜːʃl/", meaning: "有争议的", category: "media", distractors: ["公认的", "普遍接受的", "无争议的"] },
    { word: "distorted", phonetic: "/dɪˈstɔːtɪd/", meaning: "扭曲的", category: "media", distractors: ["真实的", "准确的", "客观的"] },
    { word: "emphasize", phonetic: "/ˈemfəsaɪz/", meaning: "强调", category: "media", distractors: ["忽视", "轻视", "淡化"] },
    { word: "headline", phonetic: "/ˈhedlaɪn/", meaning: "标题", category: "media", distractors: ["正文", "结尾", "注释"] },
    { word: "impartial", phonetic: "/ɪmˈpɑːʃl/", meaning: "公正的", category: "media", distractors: ["偏袒的", "片面的", "主观的"] },
    { word: "imply", phonetic: "/ɪmˈplaɪ/", meaning: "暗示", category: "media", distractors: ["明说", "直言", "声明"] },
    { word: "infamous", phonetic: "/ˈɪnfəməs/", meaning: "臭名昭著的", category: "media", distractors: ["著名的", "受尊敬的", "受欢迎的"] },
    { word: "inform", phonetic: "/ɪnˈfɔːm/", meaning: "通知", category: "media", distractors: ["隐瞒", "隐藏", "保密"] },
    { word: "manipulate", phonetic: "/məˈnɪpjuleɪt/", meaning: "操纵", category: "media", distractors: ["客观报道", "真实呈现", "如实反映"] },
    { word: "medium", phonetic: "/ˈmiːdiəm/", meaning: "媒介", category: "media", distractors: ["来源", "内容", "结果"] },
    { word: "paparazzi", phonetic: "/ˌpæpəˈrætsi/", meaning: "狗仔队", category: "media", distractors: ["记者", "编辑", "作家"] },
    { word: "scrutinize", phonetic: "/ˈskruːtənaɪz/", meaning: "仔细检查", category: "media", distractors: ["忽视", "忽略", "粗略看"] },
    { word: "sensational", phonetic: "/senˈseɪʃənl/", meaning: "轰动的", category: "media", distractors: ["普通的", "平淡的", "无聊的"] },
    { word: "speculate", phonetic: "/ˈspekjuleɪt/", meaning: "推测", category: "media", distractors: ["确定", "证实", "核实"] },
    { word: "spotlight", phonetic: "/ˈspɒtlaɪt/", meaning: "聚光灯", category: "media", distractors: ["阴影", "暗处", "背景"] },
    { word: "tabloid", phonetic: "/ˈtæblɔɪd/", meaning: "小报", category: "media", distractors: ["大报", "官媒", "严肃媒体"] },
    { word: "verify", phonetic: "/ˈverɪfaɪ/", meaning: "核实", category: "media", distractors: ["忽略", "假设", "猜测"] },
    { word: "viewer", phonetic: "/ˈvjuːər/", meaning: "观众", category: "media", distractors: ["演员", "主持人", "制作人"] },

    // ===== 艺术 Art =====
    { word: "atmosphere", phonetic: "/ˈætməsfɪər/", meaning: "气氛", category: "art", distractors: ["真空", "空白", "沉闷"] },
    { word: "audience", phonetic: "/ˈɔːdiəns/", meaning: "观众", category: "art", distractors: ["表演者", "导演", "作者"] },
    { word: "collect", phonetic: "/kəˈlekt/", meaning: "收集", category: "art", distractors: ["分散", "丢弃", "遗失"] },
    { word: "comical", phonetic: "/ˈkɒmɪkl/", meaning: "滑稽的", category: "art", distractors: ["严肃的", "悲伤的", "沉重的"] },
    { word: "dramatic", phonetic: "/drəˈmætɪk/", meaning: "戏剧性的", category: "art", distractors: ["平淡的", "无聊的", "单调的"] },
    { word: "entertaining", phonetic: "/ˌentəˈteɪnɪŋ/", meaning: "有趣的", category: "art", distractors: ["无聊的", "乏味的", "枯燥的"] },
    { word: "escapism", phonetic: "/ɪˈskeɪpɪzəm/", meaning: "逃避现实", category: "art", distractors: ["面对现实", "接受现实", "直面困难"] },
    { word: "exhibition", phonetic: "/ˌeksɪˈbɪʃn/", meaning: "展览", category: "art", distractors: ["收藏", "储存", "隐藏"] },
    { word: "hobby", phonetic: "/ˈhɒbi/", meaning: "爱好", category: "art", distractors: ["工作", "职责", "义务"] },
    { word: "influence", phonetic: "/ˈɪnfluəns/", meaning: "影响", category: "art", distractors: ["忽视", "无关", "独立"] },
    { word: "inspire", phonetic: "/ɪnˈspaɪər/", meaning: "激励", category: "art", distractors: ["打击", "挫败", "阻碍"] },
    { word: "interactive", phonetic: "/ˌɪntərˈæktɪv/", meaning: "互动的", category: "art", distractors: ["被动的", "单向的", "静态的"] },
    { word: "lively", phonetic: "/ˈlaɪvli/", meaning: "活泼的", category: "art", distractors: ["沉闷的", "死板的", "无趣的"] },
    { word: "moving", phonetic: "/ˈmuːvɪŋ/", meaning: "感人的", category: "art", distractors: ["无聊的", "冷漠的", "麻木的"] },
    { word: "outing", phonetic: "/ˈaʊtɪŋ/", meaning: "郊游", category: "art", distractors: ["宅家", "室内", "工作"] },
    { word: "participate", phonetic: "/pɑːˈtɪsɪpeɪt/", meaning: "参与", category: "art", distractors: ["旁观", "不参与", "缺席"] },
    { word: "pastime", phonetic: "/ˈpɑːstaɪm/", meaning: "消遣", category: "art", distractors: ["工作", "责任", "义务"] },
    { word: "perform", phonetic: "/pəˈfɔːm/", meaning: "表演", category: "art", distractors: ["观看", "欣赏", "评论"] },
    { word: "sacrifice", phonetic: "/ˈsækrɪfaɪs/", meaning: "牺牲", category: "art", distractors: ["获得", "收益", "利益"] },
    { word: "spectator", phonetic: "/spekˈteɪtər/", meaning: "观众", category: "art", distractors: ["演员", "运动员", "参与者"] },
    { word: "subjective", phonetic: "/səbˈdʒektɪv/", meaning: "主观的", category: "art", distractors: ["客观的", "事实的", "科学的"] },
    { word: "tedious", phonetic: "/ˈtiːdiəs/", meaning: "乏味的", category: "art", distractors: ["有趣的", "精彩的", "吸引的"] },
    { word: "venue", phonetic: "/ˈvenjuː/", meaning: "场地", category: "art", distractors: ["观众", "演员", "节目"] },

    // ===== 变化 Changes =====
    { word: "abrupt", phonetic: "/əˈbrʌpt/", meaning: "突然的", category: "changes", distractors: ["渐进的", "缓慢的", "温和的"] },
    { word: "considerable", phonetic: "/kənˈsɪdərəbl/", meaning: "相当大的", category: "changes", distractors: ["微小的", "轻微的", "不重要的"] },
    { word: "consistently", phonetic: "/kənˈsɪstəntli/", meaning: "一贯地", category: "changes", distractors: ["偶尔地", "不定地", "随机地"] },
    { word: "endure", phonetic: "/ɪnˈdjʊər/", meaning: "忍受", category: "changes", distractors: ["放弃", "逃避", "投降"] },
    { word: "gradual", phonetic: "/ˈɡrædʒuəl/", meaning: "渐进的", category: "changes", distractors: ["突然的", "急剧的", "立即的"] },
    { word: "imminent", phonetic: "/ˈɪmɪnənt/", meaning: "即将发生的", category: "changes", distractors: ["遥远的", "不确定的", "过去的"] },
    { word: "imperceptible", phonetic: "/ˌɪmpəˈseptəbl/", meaning: "察觉不到的", category: "changes", distractors: ["明显的", "显著的", "突出的"] },
    { word: "insignificant", phonetic: "/ˌɪnsɪɡˈnɪfɪkənt/", meaning: "微不足道的", category: "changes", distractors: ["重要的", "重大的", "关键的"] },
    { word: "instantly", phonetic: "/ˈɪnstəntli/", meaning: "立即地", category: "changes", distractors: ["缓慢地", "逐渐地", "延迟地"] },
    { word: "minute", phonetic: "/maɪˈnjuːt/", meaning: "微小的", category: "changes", distractors: ["巨大的", "显著的", "重要的"] },
    { word: "moderate", phonetic: "/ˈmɒdərət/", meaning: "适度的", category: "changes", distractors: ["极端的", "过度的", "激烈的"] },
    { word: "persist", phonetic: "/pəˈsɪst/", meaning: "坚持", category: "changes", distractors: ["放弃", "停止", "中断"] },
    { word: "preceding", phonetic: "/prɪˈsiːdɪŋ/", meaning: "之前的", category: "changes", distractors: ["之后的", "随后的", "未来的"] },
    { word: "remnant", phonetic: "/ˈremnənt/", meaning: "残余", category: "changes", distractors: ["整体", "全部", "完整"] },
    { word: "retrospect", phonetic: "/ˈretrəspekt/", meaning: "回顾", category: "changes", distractors: ["展望", "预测", "未来"] },
    { word: "shift", phonetic: "/ʃɪft/", meaning: "转变", category: "changes", distractors: ["稳定", "保持", "不变"] },
    { word: "subtle", phonetic: "/ˈsʌtl/", meaning: "微妙的", category: "changes", distractors: ["明显的", "显著的", "突出的"] },
    { word: "temporary", phonetic: "/ˈtemprəri/", meaning: "临时的", category: "changes", distractors: ["永久的", "持久的", "长期的"] },
    { word: "turbulent", phonetic: "/ˈtɜːbjələnt/", meaning: "动荡的", category: "changes", distractors: ["平静的", "稳定的", "安宁的"] },

    // ===== 数据描述 Data =====
    { word: "anticipated", phonetic: "/ænˈtɪsɪpeɪtɪd/", meaning: "预期的", category: "data", distractors: ["意外的", "突然的", "未料到的"] },
    { word: "comparison", phonetic: "/kəmˈpærɪsn/", meaning: "比较", category: "data", distractors: ["单独分析", "孤立研究", "独立评估"] },
    { word: "decline", phonetic: "/dɪˈklaɪn/", meaning: "下降", category: "data", distractors: ["上升", "增长", "攀升"] },
    { word: "fluctuate", phonetic: "/ˈflʌktʃueɪt/", meaning: "波动", category: "data", distractors: ["稳定", "保持", "不变"] },
    { word: "forecast", phonetic: "/ˈfɔːkɑːst/", meaning: "预测", category: "data", distractors: ["回顾", "总结", "历史"] },
    { word: "indicate", phonetic: "/ˈɪndɪkeɪt/", meaning: "表明", category: "data", distractors: ["隐藏", "掩盖", "忽略"] },
    { word: "marked", phonetic: "/mɑːkt/", meaning: "显著的", category: "data", distractors: ["轻微的", "不明显的", "微小的"] },
    { word: "noticeable", phonetic: "/ˈnəʊtɪsəbl/", meaning: "明显的", category: "data", distractors: ["不明显的", "微小的", "难察觉的"] },
    { word: "plateaued", phonetic: "/ˈplætəʊd/", meaning: "停滞", category: "data", distractors: ["上升", "下降", "波动"] },
    { word: "previous", phonetic: "/ˈpriːviəs/", meaning: "之前的", category: "data", distractors: ["之后的", "随后的", "未来的"] },
    { word: "proportion", phonetic: "/prəˈpɔːʃn/", meaning: "比例", category: "data", distractors: ["整体", "全部", "总数"] },
    { word: "reach", phonetic: "/riːtʃ/", meaning: "达到", category: "data", distractors: ["未到", "失败", "落后"] },
    { word: "relatively", phonetic: "/ˈrelətɪvli/", meaning: "相对地", category: "data", distractors: ["绝对地", "完全地", "极度地"] },
    { word: "repeatedly", phonetic: "/rɪˈpiːtɪdli/", meaning: "反复地", category: "data", distractors: ["一次性", "偶尔", "罕见地"] },
    { word: "steep", phonetic: "/stiːp/", meaning: "急剧的", category: "data", distractors: ["平缓的", "温和的", "渐进的"] },
    { word: "upward", phonetic: "/ˈʌpwəd/", meaning: "向上的", category: "data", distractors: ["向下的", "下降的", "减少的"] },
    { word: "variation", phonetic: "/ˌveəriˈeɪʃn/", meaning: "变化", category: "data", distractors: ["稳定", "恒定", "不变"] },

    // ===== 写作功能词 Writing =====
    { word: "challenge", phonetic: "/ˈtʃælɪndʒ/", meaning: "挑战", category: "writing", distractors: ["机会", "优势", "简单"] },
    { word: "consequently", phonetic: "/ˈkɒnsɪkwəntli/", meaning: "因此", category: "writing", distractors: ["然而", "但是", "相反"] },
    { word: "definitely", phonetic: "/ˈdefɪnətli/", meaning: "肯定地", category: "writing", distractors: ["可能", "也许", "不确定"] },
    { word: "furthermore", phonetic: "/ˈfɜːðəmɔːr/", meaning: "此外", category: "writing", distractors: ["然而", "相反", "但是"] },
    { word: "moreover", phonetic: "/mɔːrˈəʊvər/", meaning: "而且", category: "writing", distractors: ["然而", "但是", "相反"] },
    { word: "nevertheless", phonetic: "/ˌnevəðəˈles/", meaning: "然而，不过", category: "writing", distractors: ["因此", "所以", "结果"] },
    { word: "notion", phonetic: "/ˈnəʊʃn/", meaning: "概念，观念", category: "writing", distractors: ["事实", "证据", "现实"] },
    { word: "overall", phonetic: "/ˌəʊvərˈɔːl/", meaning: "总体而言", category: "writing", distractors: ["具体来说", "特别是", "部分地"] },
    { word: "whereas", phonetic: "/weərˈæz/", meaning: "然而，鉴于", category: "writing", distractors: ["同样", "类似", "相同"] },

    // ===== 听力高频形容词 Adjectives =====
    { word: "affordable", phonetic: "/əˈfɔːdəbl/", meaning: "负担得起的", category: "adjectives", distractors: ["昂贵的", "奢侈的", "高价的"] },
    { word: "ancient", phonetic: "/ˈeɪnʃənt/", meaning: "古老的", category: "adjectives", distractors: ["现代的", "新的", "当代的"] },
    { word: "comfortable", phonetic: "/ˈkʌmftəbl/", meaning: "舒适的", category: "adjectives", distractors: ["不舒服的", "难受的", "拥挤的"] },
    { word: "confident", phonetic: "/ˈkɒnfɪdənt/", meaning: "自信的", category: "adjectives", distractors: ["不自信的", "怀疑的", "犹豫的"] },
    { word: "convenient", phonetic: "/kənˈviːniənt/", meaning: "方便的", category: "adjectives", distractors: ["不方便的", "困难的", "麻烦的"] },
    { word: "dull", phonetic: "/dʌl/", meaning: "乏味的", category: "adjectives", distractors: ["有趣的", "精彩的", "生动的"] },
    { word: "energetic", phonetic: "/ˌenəˈdʒetɪk/", meaning: "精力充沛的", category: "adjectives", distractors: ["疲惫的", "懒散的", "无力的"] },
    { word: "exciting", phonetic: "/ɪkˈsaɪtɪŋ/", meaning: "令人兴奋的", category: "adjectives", distractors: ["无聊的", "平淡的", "乏味的"] },
    { word: "extinct", phonetic: "/ɪkˈstɪŋkt/", meaning: "灭绝的", category: "adjectives", distractors: ["繁荣的", "存活的", "增长的"] },
    { word: "fabulous", phonetic: "/ˈfæbjələs/", meaning: "极好的", category: "adjectives", distractors: ["糟糕的", "普通的", "平庸的"] },
    { word: "fantastic", phonetic: "/fænˈtæstɪk/", meaning: "极好的", category: "adjectives", distractors: ["糟糕的", "差劲的", "一般的"] },
    { word: "flexible", phonetic: "/ˈfleksəbl/", meaning: "灵活的", category: "adjectives", distractors: ["僵硬的", "固定的", "死板的"] },
    { word: "immense", phonetic: "/ɪˈmens/", meaning: "巨大的", category: "adjectives", distractors: ["微小的", "渺小的", "不重要的"] },
    { word: "intact", phonetic: "/ɪnˈtækt/", meaning: "完整的", category: "adjectives", distractors: ["破损的", "残缺的", "不完整的"] },
    { word: "intensive", phonetic: "/ɪnˈtensɪv/", meaning: "密集的", category: "adjectives", distractors: ["稀疏的", "分散的", "轻松的"] },
    { word: "knowledgeable", phonetic: "/ˈnɒlɪdʒəbl/", meaning: "博学的", category: "adjectives", distractors: ["无知的", "愚昧的", "不了解的"] },
    { word: "necessary", phonetic: "/ˈnesəsəri/", meaning: "必要的", category: "adjectives", distractors: ["不必要的", "多余的", "可选的"] },
    { word: "optimistic", phonetic: "/ˌɒptɪˈmɪstɪk/", meaning: "乐观的", category: "adjectives", distractors: ["悲观的", "消极的", "绝望的"] },
    { word: "permanent", phonetic: "/ˈpɜːmənənt/", meaning: "永久的", category: "adjectives", distractors: ["临时的", "暂时的", "短期的"] },
    { word: "pessimistic", phonetic: "/ˌpesɪˈmɪstɪk/", meaning: "悲观的", category: "adjectives", distractors: ["乐观的", "积极的", "充满希望的"] },
    { word: "practical", phonetic: "/ˈpræktɪkl/", meaning: "实用的", category: "adjectives", distractors: ["不实用的", "理论的", "空想的"] },
    { word: "realistic", phonetic: "/ˌrɪəˈlɪstɪk/", meaning: "现实的", category: "adjectives", distractors: ["不现实的", "理想的", "梦幻的"] },
    { word: "suitable", phonetic: "/ˈsuːtəbl/", meaning: "合适的", category: "adjectives", distractors: ["不合适的", "不当的", "不匹配的"] },
    { word: "tranquil", phonetic: "/ˈtræŋkwɪl/", meaning: "平静的", category: "adjectives", distractors: ["喧闹的", "混乱的", "动荡的"] },
    { word: "various", phonetic: "/ˈveəriəs/", meaning: "各种各样的", category: "adjectives", distractors: ["单一的", "相同的", "统一的"] },
    { word: "vast", phonetic: "/vɑːst/", meaning: "广阔的", category: "adjectives", distractors: ["狭小的", "有限的", "局限的"] },
    { word: "mandatory", phonetic: "/ˈmændətəri/", meaning: "强制的", category: "adjectives", distractors: ["可选的", "自愿的", "非强制的"] }
];
