// 雅思词库 Part 2 - 话题词汇 (Topics 13-25) + 听力高频词汇
var vocabularyPart2 = [
    // ===== 机器 Machines =====
    { word: "accelerate", phonetic: "/əkˈseləreɪt/", meaning: "加速", category: "machines", distractors: ["减速", "停止", "暂停"] },
    { word: "consumer", phonetic: "/kənˈsjuːmər/", meaning: "消费者", category: "machines", distractors: ["生产者", "制造商", "供应商"] },
    { word: "consumerism", phonetic: "/kənˈsjuːmərɪzəm/", meaning: "消费主义", category: "machines", distractors: ["节俭主义", "环保主义", "极简主义"] },
    { word: "convey", phonetic: "/kənˈveɪ/", meaning: "传达", category: "machines", distractors: ["隐藏", "掩盖", "保留"] },
    { word: "discard", phonetic: "/dɪsˈkɑːd/", meaning: "丢弃", category: "machines", distractors: ["保留", "收藏", "珍惜"] },
    { word: "impractical", phonetic: "/ɪmˈpræktɪkl/", meaning: "不切实际的", category: "machines", distractors: ["实际的", "可行的", "实用的"] },
    { word: "impulsive", phonetic: "/ɪmˈpʌlsɪv/", meaning: "冲动的", category: "machines", distractors: ["谨慎的", "理性的", "深思熟虑的"] },
    { word: "lasting", phonetic: "/ˈlɑːstɪŋ/", meaning: "持久的", category: "machines", distractors: ["短暂的", "临时的", "瞬间的"] },
    { word: "manually", phonetic: "/ˈmænjuəli/", meaning: "手工地", category: "machines", distractors: ["自动地", "机械地", "电子地"] },
    { word: "manufactured", phonetic: "/ˌmænjuˈfæktʃəd/", meaning: "制造的", category: "machines", distractors: ["天然的", "自然的", "原始的"] },
    { word: "mass-produced", phonetic: "/ˌmæs prəˈdjuːst/", meaning: "大量生产的", category: "machines", distractors: ["手工制作的", "定制的", "独特的"] },
    { word: "operate", phonetic: "/ˈɒpəreɪt/", meaning: "操作", category: "machines", distractors: ["停止", "关闭", "暂停"] },
    { word: "purchase", phonetic: "/ˈpɜːtʃəs/", meaning: "购买", category: "machines", distractors: ["出售", "赠送", "丢弃"] },
    { word: "rotate", phonetic: "/rəʊˈteɪt/", meaning: "旋转", category: "machines", distractors: ["静止", "固定", "停止"] },
    { word: "technique", phonetic: "/tekˈniːk/", meaning: "技术", category: "machines", distractors: ["理论", "概念", "想法"] },
    { word: "trendy", phonetic: "/ˈtrendi/", meaning: "时尚的", category: "machines", distractors: ["过时的", "老旧的", "落伍的"] },

    // ===== 时尚 Fashion =====
    { word: "disposable", phonetic: "/dɪˈspəʊzəbl/", meaning: "一次性的", category: "fashion", distractors: ["可重复使用的", "耐用的", "持久的"] },
    { word: "donate", phonetic: "/dəʊˈneɪt/", meaning: "捐赠", category: "fashion", distractors: ["索取", "保留", "占有"] },
    { word: "emerge", phonetic: "/ɪˈmɜːdʒ/", meaning: "出现", category: "fashion", distractors: ["消失", "隐藏", "退出"] },
    { word: "ethical", phonetic: "/ˈeθɪkl/", meaning: "道德的", category: "fashion", distractors: ["不道德的", "违法的", "不正当的"] },
    { word: "impulse", phonetic: "/ˈɪmpʌls/", meaning: "冲动", category: "fashion", distractors: ["理性", "谨慎", "深思"] },
    { word: "individuality", phonetic: "/ˌɪndɪˌvɪdʒuˈæləti/", meaning: "个性", category: "fashion", distractors: ["一致性", "从众", "统一"] },
    { word: "manufacturer", phonetic: "/ˌmænjuˈfæktʃərər/", meaning: "制造商", category: "fashion", distractors: ["消费者", "用户", "买家"] },
    { word: "material", phonetic: "/məˈtɪəriəl/", meaning: "材料", category: "fashion", distractors: ["成品", "产品", "结果"] },
    { word: "possessions", phonetic: "/pəˈzeʃnz/", meaning: "财产", category: "fashion", distractors: ["债务", "负担", "损失"] },
    { word: "second-hand", phonetic: "/ˌsekənd ˈhænd/", meaning: "二手的", category: "fashion", distractors: ["全新的", "原装的", "崭新的"] },

    // ===== 城市 City =====
    { word: "affluent", phonetic: "/ˈæfluənt/", meaning: "富裕的", category: "city", distractors: ["贫穷的", "贫困的", "落后的"] },
    { word: "amenities", phonetic: "/əˈmiːnətiz/", meaning: "便利设施", category: "city", distractors: ["障碍", "困难", "不便"] },
    { word: "apartment", phonetic: "/əˈpɑːtmənt/", meaning: "公寓", category: "city", distractors: ["别墅", "农舍", "平房"] },
    { word: "commute", phonetic: "/kəˈmjuːt/", meaning: "通勤", category: "city", distractors: ["居住", "工作", "休息"] },
    { word: "congested", phonetic: "/kənˈdʒestɪd/", meaning: "拥挤的", category: "city", distractors: ["空旷的", "畅通的", "宽敞的"] },
    { word: "deprived", phonetic: "/dɪˈpraɪvd/", meaning: "贫困的", category: "city", distractors: ["富裕的", "繁荣的", "发达的"] },
    { word: "downtown", phonetic: "/ˌdaʊnˈtaʊn/", meaning: "市中心", category: "city", distractors: ["郊区", "乡村", "偏远地区"] },
    { word: "flat", phonetic: "/flæt/", meaning: "公寓", category: "city", distractors: ["别墅", "独栋", "农舍"] },
    { word: "homelessness", phonetic: "/ˈhəʊmləsnəs/", meaning: "无家可归", category: "city", distractors: ["安居", "定居", "住房"] },
    { word: "imbalance", phonetic: "/ɪmˈbæləns/", meaning: "不平衡", category: "city", distractors: ["平衡", "均衡", "稳定"] },
    { word: "inadequate", phonetic: "/ɪnˈædɪkwət/", meaning: "不足的", category: "city", distractors: ["充足的", "足够的", "丰富的"] },
    { word: "infrastructure", phonetic: "/ˈɪnfrəstrʌktʃər/", meaning: "基础设施", category: "city", distractors: ["装饰", "外观", "表面"] },
    { word: "isolated", phonetic: "/ˈaɪsəleɪtɪd/", meaning: "孤立的", category: "city", distractors: ["连接的", "融合的", "统一的"] },
    { word: "neighborhood", phonetic: "/ˈneɪbəhʊd/", meaning: "社区", category: "city", distractors: ["个人", "孤立", "隔离"] },
    { word: "outskirts", phonetic: "/ˈaʊtskɜːts/", meaning: "郊区", category: "city", distractors: ["市中心", "核心区", "商业区"] },
    { word: "overpopulated", phonetic: "/ˌəʊvəˈpɒpjuleɪtɪd/", meaning: "人口过多的", category: "city", distractors: ["人口稀少的", "空旷的", "荒凉的"] },
    { word: "overwhelmed", phonetic: "/ˌəʊvəˈwelmd/", meaning: "不堪重负的", category: "city", distractors: ["轻松的", "悠闲的", "从容的"] },
    { word: "pavement", phonetic: "/ˈpeɪvmənt/", meaning: "人行道", category: "city", distractors: ["车道", "公路", "高速"] },
    { word: "pedestrian", phonetic: "/pəˈdestriən/", meaning: "行人", category: "city", distractors: ["司机", "乘客", "骑手"] },
    { word: "poverty", phonetic: "/ˈpɒvəti/", meaning: "贫穷", category: "city", distractors: ["富裕", "繁荣", "财富"] },
    { word: "rural", phonetic: "/ˈrʊərəl/", meaning: "农村的", category: "city", distractors: ["城市的", "都市的", "现代的"] },
    { word: "sanitation", phonetic: "/ˌsænɪˈteɪʃn/", meaning: "卫生设施", category: "city", distractors: ["污染", "肮脏", "不洁"] },
    { word: "shortage", phonetic: "/ˈʃɔːtɪdʒ/", meaning: "短缺", category: "city", distractors: ["过剩", "充足", "丰富"] },
    { word: "slums", phonetic: "/slʌmz/", meaning: "贫民窟", category: "city", distractors: ["豪宅", "别墅区", "高档区"] },
    { word: "suburb", phonetic: "/ˈsʌbɜːb/", meaning: "郊区", category: "city", distractors: ["市中心", "商业区", "工业区"] },
    { word: "transportation", phonetic: "/ˌtrænspɔːˈteɪʃn/", meaning: "交通", category: "city", distractors: ["静止", "停滞", "固定"] },
    { word: "urban", phonetic: "/ˈɜːbən/", meaning: "城市的", category: "city", distractors: ["农村的", "乡村的", "偏远的"] },

    // ===== 环境 Environment =====
    { word: "abruptly", phonetic: "/əˈbrʌptli/", meaning: "突然地", category: "environment", distractors: ["逐渐地", "缓慢地", "渐进地"] },
    { word: "agriculture", phonetic: "/ˈæɡrɪkʌltʃər/", meaning: "农业", category: "environment", distractors: ["工业", "商业", "服务业"] },
    { word: "arid", phonetic: "/ˈærɪd/", meaning: "干旱的", category: "environment", distractors: ["潮湿的", "多雨的", "湿润的"] },
    { word: "balmy", phonetic: "/ˈbɑːmi/", meaning: "温和的", category: "environment", distractors: ["寒冷的", "炎热的", "极端的"] },
    { word: "chilly", phonetic: "/ˈtʃɪli/", meaning: "寒冷的", category: "environment", distractors: ["温暖的", "炎热的", "宜人的"] },
    { word: "cultivate", phonetic: "/ˈkʌltɪveɪt/", meaning: "培养", category: "environment", distractors: ["破坏", "忽视", "放弃"] },
    { word: "deforestation", phonetic: "/ˌdiːˌfɒrɪˈsteɪʃn/", meaning: "砍伐森林", category: "environment", distractors: ["植树造林", "森林保护", "生态恢复"] },
    { word: "degrade", phonetic: "/dɪˈɡreɪd/", meaning: "退化", category: "environment", distractors: ["改善", "提升", "进步"] },
    { word: "disaster", phonetic: "/dɪˈzɑːstər/", meaning: "灾难", category: "environment", distractors: ["幸运", "幸福", "成功"] },
    { word: "dramatically", phonetic: "/drəˈmætɪkli/", meaning: "戏剧性地", category: "environment", distractors: ["轻微地", "缓慢地", "逐渐地"] },
    { word: "ecosystem", phonetic: "/ˈiːkəʊsɪstəm/", meaning: "生态系统", category: "environment", distractors: ["工厂", "城市", "建筑"] },
    { word: "emissions", phonetic: "/ɪˈmɪʃnz/", meaning: "排放", category: "environment", distractors: ["吸收", "净化", "过滤"] },
    { word: "erosion", phonetic: "/ɪˈrəʊʒn/", meaning: "侵蚀", category: "environment", distractors: ["保护", "加固", "增强"] },
    { word: "evolve", phonetic: "/ɪˈvɒlv/", meaning: "进化", category: "environment", distractors: ["退化", "消失", "停滞"] },
    { word: "gradually", phonetic: "/ˈɡrædʒuəli/", meaning: "逐渐地", category: "environment", distractors: ["突然地", "立即地", "瞬间地"] },
    { word: "hazardous", phonetic: "/ˈhæzədəs/", meaning: "危险的", category: "environment", distractors: ["安全的", "无害的", "友好的"] },
    { word: "intervene", phonetic: "/ˌɪntəˈviːn/", meaning: "干预", category: "environment", distractors: ["忽视", "放任", "旁观"] },
    { word: "irrigation", phonetic: "/ˌɪrɪˈɡeɪʃn/", meaning: "灌溉", category: "environment", distractors: ["干旱", "缺水", "排水"] },
    { word: "logging", phonetic: "/ˈlɒɡɪŋ/", meaning: "伐木", category: "environment", distractors: ["植树", "造林", "保护"] },
    { word: "mammal", phonetic: "/ˈmæml/", meaning: "哺乳动物", category: "environment", distractors: ["爬行动物", "鸟类", "昆虫"] },
    { word: "mediterranean", phonetic: "/ˌmedɪtəˈreɪniən/", meaning: "地中海的", category: "environment", distractors: ["热带的", "极地的", "沙漠的"] },
    { word: "mist", phonetic: "/mɪst/", meaning: "薄雾", category: "environment", distractors: ["晴朗", "阳光", "清晰"] },
    { word: "muggy", phonetic: "/ˈmʌɡi/", meaning: "闷热的", category: "environment", distractors: ["凉爽的", "干燥的", "舒适的"] },
    { word: "pesticide", phonetic: "/ˈpestɪsaɪd/", meaning: "杀虫剂", category: "environment", distractors: ["有机肥", "天然物", "生物剂"] },
    { word: "pollutant", phonetic: "/pəˈluːtənt/", meaning: "污染物", category: "environment", distractors: ["净化剂", "清洁剂", "保护剂"] },
    { word: "pollution", phonetic: "/pəˈluːʃn/", meaning: "污染", category: "environment", distractors: ["净化", "清洁", "保护"] },
    { word: "renewable", phonetic: "/rɪˈnjuːəbl/", meaning: "可再生的", category: "environment", distractors: ["不可再生的", "有限的", "枯竭的"] },
    { word: "safeguard", phonetic: "/ˈseɪfɡɑːd/", meaning: "保护", category: "environment", distractors: ["危害", "破坏", "威胁"] },
    { word: "seasonal", phonetic: "/ˈsiːzənl/", meaning: "季节性的", category: "environment", distractors: ["全年的", "永久的", "持续的"] },
    { word: "significantly", phonetic: "/sɪɡˈnɪfɪkəntli/", meaning: "显著地", category: "environment", distractors: ["轻微地", "稍微地", "略微地"] },
    { word: "sleet", phonetic: "/sliːt/", meaning: "雨夹雪", category: "environment", distractors: ["晴天", "阳光", "干燥"] },
    { word: "soil", phonetic: "/sɔɪl/", meaning: "土壤", category: "environment", distractors: ["空气", "水", "岩石"] },
    { word: "species", phonetic: "/ˈspiːʃiːz/", meaning: "物种", category: "environment", distractors: ["个体", "样本", "标本"] },
    { word: "sustainable", phonetic: "/səˈsteɪnəbl/", meaning: "可持续的", category: "environment", distractors: ["短期的", "一次性的", "消耗性的"] },
    { word: "temperate", phonetic: "/ˈtempərət/", meaning: "温带的", category: "environment", distractors: ["热带的", "寒带的", "极端的"] },
    { word: "tropical", phonetic: "/ˈtrɒpɪkl/", meaning: "热带的", category: "environment", distractors: ["寒带的", "温带的", "极地的"] },
    { word: "unprecedented", phonetic: "/ʌnˈpresɪdentɪd/", meaning: "史无前例的", category: "environment", distractors: ["常见的", "普通的", "惯例的"] },
    { word: "urgent", phonetic: "/ˈɜːdʒənt/", meaning: "紧急的", category: "environment", distractors: ["不急的", "缓慢的", "闲散的"] },
    { word: "vegetation", phonetic: "/ˌvedʒəˈteɪʃn/", meaning: "植被", category: "environment", distractors: ["建筑", "道路", "设施"] },
    { word: "vital", phonetic: "/ˈvaɪtl/", meaning: "至关重要的", category: "environment", distractors: ["不重要的", "次要的", "可选的"] },
    { word: "climate", phonetic: "/ˈklaɪmət/", meaning: "气候", category: "environment", distractors: ["天气", "温度", "季节"] },

    // ===== 能源 Energy =====
    { word: "abundant", phonetic: "/əˈbʌndənt/", meaning: "丰富的", category: "energy", distractors: ["稀缺的", "有限的", "不足的"] },
    { word: "achievable", phonetic: "/əˈtʃiːvəbl/", meaning: "可实现的", category: "energy", distractors: ["不可能的", "虚幻的", "理想的"] },
    { word: "alternative", phonetic: "/ɔːlˈtɜːnətɪv/", meaning: "替代的", category: "energy", distractors: ["传统的", "常规的", "唯一的"] },
    { word: "biofuels", phonetic: "/ˈbaɪəʊfjuːəlz/", meaning: "生物燃料", category: "energy", distractors: ["化石燃料", "石油", "煤炭"] },
    { word: "consumption", phonetic: "/kənˈsʌmpʃn/", meaning: "消费", category: "energy", distractors: ["生产", "储存", "节约"] },
    { word: "curb", phonetic: "/kɜːb/", meaning: "控制，抑制", category: "energy", distractors: ["增加", "放任", "扩大"] },
    { word: "exploit", phonetic: "/ɪkˈsplɔɪt/", meaning: "开发利用", category: "energy", distractors: ["保护", "保存", "节约"] },
    { word: "finite", phonetic: "/ˈfaɪnaɪt/", meaning: "有限的", category: "energy", distractors: ["无限的", "永恒的", "持久的"] },
    { word: "generate", phonetic: "/ˈdʒenəreɪt/", meaning: "产生", category: "energy", distractors: ["消耗", "使用", "减少"] },
    { word: "harness", phonetic: "/ˈhɑːnəs/", meaning: "利用", category: "energy", distractors: ["浪费", "忽视", "放弃"] },
    { word: "maximize", phonetic: "/ˈmæksɪmaɪz/", meaning: "最大化", category: "energy", distractors: ["最小化", "减少", "限制"] },
    { word: "mining", phonetic: "/ˈmaɪnɪŋ/", meaning: "采矿", category: "energy", distractors: ["保护", "恢复", "绿化"] },
    { word: "regulate", phonetic: "/ˈreɡjuleɪt/", meaning: "调节", category: "energy", distractors: ["放任", "忽视", "无序"] },
    { word: "scarce", phonetic: "/skeəs/", meaning: "稀缺的", category: "energy", distractors: ["丰富的", "充足的", "过剩的"] },
    { word: "squander", phonetic: "/ˈskwɒndər/", meaning: "浪费", category: "energy", distractors: ["节约", "储存", "保护"] },
    { word: "supply", phonetic: "/səˈplaɪ/", meaning: "供应", category: "energy", distractors: ["需求", "消耗", "缺乏"] },
    { word: "unsustainable", phonetic: "/ˌʌnsəˈsteɪnəbl/", meaning: "不可持续的", category: "energy", distractors: ["可持续的", "长久的", "稳定的"] },

    // ===== 社会议题 Issues =====
    { word: "acknowledge", phonetic: "/əkˈnɒlɪdʒ/", meaning: "承认", category: "issues", distractors: ["否认", "拒绝", "忽视"] },
    { word: "chaos", phonetic: "/ˈkeɪɒs/", meaning: "混乱", category: "issues", distractors: ["秩序", "和平", "稳定"] },
    { word: "contemplate", phonetic: "/ˈkɒntəmpleɪt/", meaning: "沉思", category: "issues", distractors: ["忽视", "无视", "草率"] },
    { word: "crisis", phonetic: "/ˈkraɪsɪs/", meaning: "危机", category: "issues", distractors: ["机遇", "稳定", "繁荣"] },
    { word: "critical", phonetic: "/ˈkrɪtɪkl/", meaning: "关键的", category: "issues", distractors: ["不重要的", "次要的", "无关的"] },
    { word: "development", phonetic: "/dɪˈveləpmənt/", meaning: "发展", category: "issues", distractors: ["退步", "衰退", "停滞"] },
    { word: "disorder", phonetic: "/dɪsˈɔːdər/", meaning: "混乱", category: "issues", distractors: ["秩序", "规范", "整齐"] },
    { word: "dispute", phonetic: "/dɪˈspjuːt/", meaning: "争论", category: "issues", distractors: ["共识", "同意", "和解"] },
    { word: "diversity", phonetic: "/daɪˈvɜːsəti/", meaning: "多样性", category: "issues", distractors: ["单一性", "统一", "同质"] },
    { word: "escalate", phonetic: "/ˈeskəleɪt/", meaning: "升级", category: "issues", distractors: ["降级", "缓和", "平息"] },
    { word: "globalization", phonetic: "/ˌɡləʊbəlaɪˈzeɪʃn/", meaning: "全球化", category: "issues", distractors: ["本土化", "孤立", "封闭"] },
    { word: "inevitable", phonetic: "/ɪnˈevɪtəbl/", meaning: "不可避免的", category: "issues", distractors: ["可避免的", "可选的", "偶然的"] },
    { word: "measures", phonetic: "/ˈmeʒəz/", meaning: "措施", category: "issues", distractors: ["问题", "困难", "障碍"] },
    { word: "ongoing", phonetic: "/ˈɒnɡəʊɪŋ/", meaning: "进行中的", category: "issues", distractors: ["结束的", "完成的", "过去的"] },
    { word: "overcome", phonetic: "/ˌəʊvəˈkʌm/", meaning: "克服", category: "issues", distractors: ["屈服", "放弃", "失败"] },
    { word: "pressing", phonetic: "/ˈpresɪŋ/", meaning: "紧迫的", category: "issues", distractors: ["不急的", "次要的", "可推迟的"] },
    { word: "scenario", phonetic: "/səˈnɑːriəʊ/", meaning: "情景", category: "issues", distractors: ["现实", "事实", "历史"] },
    { word: "tackle", phonetic: "/ˈtækl/", meaning: "解决", category: "issues", distractors: ["忽视", "逃避", "放弃"] },
    { word: "tolerate", phonetic: "/ˈtɒləreɪt/", meaning: "容忍", category: "issues", distractors: ["拒绝", "反对", "抵制"] },
    { word: "worsen", phonetic: "/ˈwɜːsn/", meaning: "恶化", category: "issues", distractors: ["改善", "好转", "进步"] },

    // ===== 商业与工作 Business =====
    { word: "ambitious", phonetic: "/æmˈbɪʃəs/", meaning: "有雄心的", category: "business", distractors: ["懒惰的", "无志向的", "安于现状的"] },
    { word: "bargain", phonetic: "/ˈbɑːɡɪn/", meaning: "讨价还价", category: "business", distractors: ["接受", "付全价", "不谈判"] },
    { word: "career", phonetic: "/kəˈrɪər/", meaning: "职业", category: "business", distractors: ["爱好", "休闲", "娱乐"] },
    { word: "colleague", phonetic: "/ˈkɒliːɡ/", meaning: "同事", category: "business", distractors: ["对手", "竞争者", "陌生人"] },
    { word: "competitive", phonetic: "/kəmˈpetətɪv/", meaning: "竞争的", category: "business", distractors: ["合作的", "友好的", "非竞争的"] },
    { word: "conditions", phonetic: "/kənˈdɪʃnz/", meaning: "条件", category: "business", distractors: ["无条件", "自由", "随意"] },
    { word: "deadline", phonetic: "/ˈdedlaɪn/", meaning: "截止日期", category: "business", distractors: ["开始日期", "中间期", "无限期"] },
    { word: "delegate", phonetic: "/ˈdelɪɡeɪt/", meaning: "委派", category: "business", distractors: ["独揽", "包办", "垄断"] },
    { word: "demanding", phonetic: "/dɪˈmɑːndɪŋ/", meaning: "要求高的", category: "business", distractors: ["轻松的", "简单的", "容易的"] },
    { word: "discount", phonetic: "/ˈdɪskaʊnt/", meaning: "折扣", category: "business", distractors: ["加价", "涨价", "原价"] },
    { word: "employee", phonetic: "/ɪmˈplɔɪiː/", meaning: "员工", category: "business", distractors: ["雇主", "老板", "经理"] },
    { word: "entrepreneur", phonetic: "/ˌɒntrəprəˈnɜːr/", meaning: "企业家", category: "business", distractors: ["员工", "职员", "工人"] },
    { word: "financial", phonetic: "/faɪˈnænʃl/", meaning: "财务的", category: "business", distractors: ["非财务的", "精神的", "情感的"] },
    { word: "flexibility", phonetic: "/ˌfleksəˈbɪləti/", meaning: "灵活性", category: "business", distractors: ["僵化", "固定", "死板"] },
    { word: "haggle", phonetic: "/ˈhæɡl/", meaning: "讨价还价", category: "business", distractors: ["接受", "同意", "付全款"] },
    { word: "leadership", phonetic: "/ˈliːdəʃɪp/", meaning: "领导力", category: "business", distractors: ["服从", "跟随", "被动"] },
    { word: "monopoly", phonetic: "/məˈnɒpəli/", meaning: "垄断", category: "business", distractors: ["竞争", "自由市场", "多元化"] },
    { word: "negotiate", phonetic: "/nɪˈɡəʊʃieɪt/", meaning: "谈判", category: "business", distractors: ["命令", "强制", "拒绝"] },
    { word: "occupation", phonetic: "/ˌɒkjuˈpeɪʃn/", meaning: "职业", category: "business", distractors: ["爱好", "休闲", "娱乐"] },
    { word: "overtime", phonetic: "/ˈəʊvətaɪm/", meaning: "加班", category: "business", distractors: ["休息", "假期", "放松"] },
    { word: "recruit", phonetic: "/rɪˈkruːt/", meaning: "招募", category: "business", distractors: ["解雇", "开除", "辞退"] },
    { word: "rewarding", phonetic: "/rɪˈwɔːdɪŋ/", meaning: "有回报的", category: "business", distractors: ["无回报的", "徒劳的", "无意义的"] },
    { word: "salary", phonetic: "/ˈsæləri/", meaning: "薪水", category: "business", distractors: ["费用", "支出", "损失"] },
    { word: "skilled", phonetic: "/skɪld/", meaning: "有技能的", category: "business", distractors: ["无技能的", "业余的", "生疏的"] },
    { word: "unskilled", phonetic: "/ˌʌnˈskɪld/", meaning: "无技能的", category: "business", distractors: ["熟练的", "专业的", "精通的"] }
];
