// 雅思词库 Part 5 - 听力高频词汇（自然、地点、形状、学科、旅游、交通、天气、运动、爱好等）
var vocabularyPart5 = [
    // ===== 自然 Nature =====
    { word: "avalanche", phonetic: "/ˈævəlɑːnʃ/", meaning: "雪崩", category: "nature", distractors: ["地震", "洪水", "台风"] },
    { word: "canyon", phonetic: "/ˈkænjən/", meaning: "峡谷", category: "nature", distractors: ["山峰", "平原", "盆地"] },
    { word: "catastrophe", phonetic: "/kəˈtæstrəfi/", meaning: "灾难", category: "nature", distractors: ["幸运", "成功", "繁荣"] },
    { word: "cliff", phonetic: "/klɪf/", meaning: "悬崖", category: "nature", distractors: ["平地", "山谷", "河流"] },
    { word: "coast", phonetic: "/kəʊst/", meaning: "海岸", category: "nature", distractors: ["内陆", "山区", "沙漠"] },
    { word: "dam", phonetic: "/dæm/", meaning: "水坝", category: "nature", distractors: ["桥梁", "隧道", "公路"] },
    { word: "desert", phonetic: "/ˈdezət/", meaning: "沙漠", category: "nature", distractors: ["森林", "草原", "湿地"] },
    { word: "drought", phonetic: "/draʊt/", meaning: "干旱", category: "nature", distractors: ["洪水", "暴雨", "潮湿"] },
    { word: "earthquake", phonetic: "/ˈɜːθkweɪk/", meaning: "地震", category: "nature", distractors: ["台风", "洪水", "火山"] },
    { word: "field", phonetic: "/fiːld/", meaning: "田野", category: "nature", distractors: ["城市", "工厂", "建筑"] },
    { word: "flood", phonetic: "/flʌd/", meaning: "洪水", category: "nature", distractors: ["干旱", "冰雹", "霜冻"] },
    { word: "forest", phonetic: "/ˈfɒrɪst/", meaning: "森林", category: "nature", distractors: ["沙漠", "草原", "城市"] },
    { word: "hill", phonetic: "/hɪl/", meaning: "小山", category: "nature", distractors: ["平原", "盆地", "峡谷"] },
    { word: "hurricane", phonetic: "/ˈhʌrɪkən/", meaning: "飓风", category: "nature", distractors: ["微风", "小雨", "晴天"] },
    { word: "island", phonetic: "/ˈaɪlənd/", meaning: "岛屿", category: "nature", distractors: ["大陆", "半岛", "海峡"] },
    { word: "jungle", phonetic: "/ˈdʒʌŋɡl/", meaning: "丛林", category: "nature", distractors: ["沙漠", "草原", "苔原"] },
    { word: "lake", phonetic: "/leɪk/", meaning: "湖泊", category: "nature", distractors: ["海洋", "河流", "池塘"] },
    { word: "landslide", phonetic: "/ˈlændslaɪd/", meaning: "山体滑坡", category: "nature", distractors: ["地震", "洪水", "台风"] },
    { word: "mountain", phonetic: "/ˈmaʊntɪn/", meaning: "山", category: "nature", distractors: ["平原", "盆地", "谷地"] },
    { word: "oasis", phonetic: "/əʊˈeɪsɪs/", meaning: "绿洲", category: "nature", distractors: ["沙漠", "荒原", "戈壁"] },
    { word: "ocean", phonetic: "/ˈəʊʃn/", meaning: "海洋", category: "nature", distractors: ["湖泊", "河流", "池塘"] },
    { word: "peninsula", phonetic: "/pəˈnɪnsjələ/", meaning: "半岛", category: "nature", distractors: ["岛屿", "大陆", "海峡"] },
    { word: "pond", phonetic: "/pɒnd/", meaning: "池塘", category: "nature", distractors: ["湖泊", "海洋", "河流"] },
    { word: "reef", phonetic: "/riːf/", meaning: "礁石", category: "nature", distractors: ["沙滩", "深海", "港口"] },
    { word: "river", phonetic: "/ˈrɪvər/", meaning: "河流", category: "nature", distractors: ["湖泊", "海洋", "池塘"] },
    { word: "storm", phonetic: "/stɔːm/", meaning: "暴风雨", category: "nature", distractors: ["晴天", "微风", "毛毛雨"] },
    { word: "tornado", phonetic: "/tɔːˈneɪdəʊ/", meaning: "龙卷风", category: "nature", distractors: ["微风", "小雨", "晴天"] },
    { word: "typhoon", phonetic: "/taɪˈfuːn/", meaning: "台风", category: "nature", distractors: ["微风", "阵雨", "多云"] },
    { word: "valley", phonetic: "/ˈvæli/", meaning: "山谷", category: "nature", distractors: ["山峰", "高原", "平原"] },
    { word: "volcano", phonetic: "/vɒlˈkeɪnəʊ/", meaning: "火山", category: "nature", distractors: ["山脉", "平原", "盆地"] },
    { word: "waterfall", phonetic: "/ˈwɔːtəfɔːl/", meaning: "瀑布", category: "nature", distractors: ["湖泊", "池塘", "河流"] },
    { word: "whale", phonetic: "/weɪl/", meaning: "鲸鱼", category: "nature", distractors: ["鲨鱼", "海豚", "海龟"] },

    // ===== 地点 Places =====
    { word: "art gallery", phonetic: "/ˈɑːt ˌɡæləri/", meaning: "美术馆", category: "places", distractors: ["博物馆", "图书馆", "剧院"] },
    { word: "ballet", phonetic: "/ˈbæleɪ/", meaning: "芭蕾舞", category: "places", distractors: ["歌剧", "话剧", "音乐会"] },
    { word: "bookshop", phonetic: "/ˈbʊkʃɒp/", meaning: "书店", category: "places", distractors: ["图书馆", "文具店", "报刊亭"] },
    { word: "cafe", phonetic: "/ˈkæfeɪ/", meaning: "咖啡馆", category: "places", distractors: ["餐厅", "酒吧", "酒店"] },
    { word: "canteen", phonetic: "/kænˈtiːn/", meaning: "食堂", category: "places", distractors: ["餐厅", "厨房", "超市"] },
    { word: "carnival", phonetic: "/ˈkɑːnɪvl/", meaning: "嘉年华", category: "places", distractors: ["葬礼", "会议", "考试"] },
    { word: "cinema", phonetic: "/ˈsɪnəmə/", meaning: "电影院", category: "places", distractors: ["剧院", "音乐厅", "博物馆"] },
    { word: "concert", phonetic: "/ˈkɒnsət/", meaning: "音乐会", category: "places", distractors: ["演讲", "会议", "考试"] },
    { word: "cottage", phonetic: "/ˈkɒtɪdʒ/", meaning: "小屋", category: "places", distractors: ["公寓", "大厦", "别墅"] },
    { word: "kindergarten", phonetic: "/ˈkɪndəɡɑːtn/", meaning: "幼儿园", category: "places", distractors: ["小学", "中学", "大学"] },
    { word: "museum", phonetic: "/mjuˈziːəm/", meaning: "博物馆", category: "places", distractors: ["图书馆", "体育馆", "电影院"] },
    { word: "orchestra", phonetic: "/ˈɔːkɪstrə/", meaning: "管弦乐队", category: "places", distractors: ["合唱团", "摇滚乐队", "独唱者"] },
    { word: "park", phonetic: "/pɑːk/", meaning: "公园", category: "places", distractors: ["广场", "街道", "建筑"] },
    { word: "parliament", phonetic: "/ˈpɑːləmənt/", meaning: "议会", category: "places", distractors: ["法院", "学校", "医院"] },
    { word: "restaurant", phonetic: "/ˈrestrɒnt/", meaning: "餐厅", category: "places", distractors: ["厨房", "食堂", "超市"] },
    { word: "sports centre", phonetic: "/ˈspɔːts ˌsentər/", meaning: "体育中心", category: "places", distractors: ["购物中心", "医疗中心", "文化中心"] },
    { word: "swimming pool", phonetic: "/ˈswɪmɪŋ puːl/", meaning: "游泳池", category: "places", distractors: ["健身房", "球场", "跑道"] },
    { word: "symphony", phonetic: "/ˈsɪmfəni/", meaning: "交响乐", category: "places", distractors: ["摇滚乐", "爵士乐", "流行乐"] },
    { word: "theatre", phonetic: "/ˈθɪətər/", meaning: "剧院", category: "places", distractors: ["电影院", "博物馆", "图书馆"] },

    // ===== 形状 Shapes =====
    { word: "altitude", phonetic: "/ˈæltɪtjuːd/", meaning: "高度", category: "shapes", distractors: ["宽度", "长度", "深度"] },
    { word: "breadth", phonetic: "/bredθ/", meaning: "宽度", category: "shapes", distractors: ["长度", "高度", "深度"] },
    { word: "circular", phonetic: "/ˈsɜːkjələr/", meaning: "圆形的", category: "shapes", distractors: ["方形的", "三角形的", "椭圆的"] },
    { word: "curved", phonetic: "/kɜːvd/", meaning: "弯曲的", category: "shapes", distractors: ["直的", "平的", "尖的"] },
    { word: "cylindrical", phonetic: "/sɪˈlɪndrɪkl/", meaning: "圆柱形的", category: "shapes", distractors: ["球形的", "立方体的", "锥形的"] },
    { word: "depth", phonetic: "/depθ/", meaning: "深度", category: "shapes", distractors: ["高度", "宽度", "长度"] },
    { word: "height", phonetic: "/haɪt/", meaning: "高度", category: "shapes", distractors: ["宽度", "长度", "深度"] },
    { word: "length", phonetic: "/leŋθ/", meaning: "长度", category: "shapes", distractors: ["宽度", "高度", "深度"] },
    { word: "oval", phonetic: "/ˈəʊvl/", meaning: "椭圆形的", category: "shapes", distractors: ["圆形的", "方形的", "三角形的"] },
    { word: "rectangular", phonetic: "/rekˈtæŋɡjələr/", meaning: "长方形的", category: "shapes", distractors: ["正方形的", "圆形的", "三角形的"] },
    { word: "spherical", phonetic: "/ˈsferɪkl/", meaning: "球形的", category: "shapes", distractors: ["立方体的", "圆柱形的", "锥形的"] },
    { word: "spiral", phonetic: "/ˈspaɪrəl/", meaning: "螺旋形的", category: "shapes", distractors: ["直线的", "曲线的", "锯齿的"] },
    { word: "square", phonetic: "/skweər/", meaning: "正方形的", category: "shapes", distractors: ["圆形的", "三角形的", "长方形的"] },
    { word: "triangular", phonetic: "/traɪˈæŋɡjələr/", meaning: "三角形的", category: "shapes", distractors: ["圆形的", "方形的", "椭圆形的"] },

    // ===== 学科 Subjects =====
    { word: "anthropology", phonetic: "/ˌænθrəˈpɒlədʒi/", meaning: "人类学", category: "subjects", distractors: ["社会学", "心理学", "经济学"] },
    { word: "archaeology", phonetic: "/ˌɑːkiˈɒlədʒi/", meaning: "考古学", category: "subjects", distractors: ["历史学", "地理学", "生物学"] },
    { word: "architecture", phonetic: "/ˈɑːkɪtektʃər/", meaning: "建筑学", category: "subjects", distractors: ["工程学", "设计学", "艺术"] },
    { word: "biology", phonetic: "/baɪˈɒlədʒi/", meaning: "生物学", category: "subjects", distractors: ["化学", "物理学", "数学"] },
    { word: "chemistry", phonetic: "/ˈkemɪstri/", meaning: "化学", category: "subjects", distractors: ["物理学", "生物学", "数学"] },
    { word: "economics", phonetic: "/ˌiːkəˈnɒmɪks/", meaning: "经济学", category: "subjects", distractors: ["政治学", "社会学", "心理学"] },
    { word: "geography", phonetic: "/dʒiˈɒɡrəfi/", meaning: "地理学", category: "subjects", distractors: ["历史学", "政治学", "生物学"] },
    { word: "history", phonetic: "/ˈhɪstri/", meaning: "历史", category: "subjects", distractors: ["地理", "政治", "经济"] },
    { word: "law", phonetic: "/lɔː/", meaning: "法律", category: "subjects", distractors: ["医学", "工程", "艺术"] },
    { word: "literature", phonetic: "/ˈlɪtrətʃər/", meaning: "文学", category: "subjects", distractors: ["语言学", "历史学", "哲学"] },
    { word: "logic", phonetic: "/ˈlɒdʒɪk/", meaning: "逻辑学", category: "subjects", distractors: ["哲学", "数学", "心理学"] },
    { word: "mathematics", phonetic: "/ˌmæθəˈmætɪks/", meaning: "数学", category: "subjects", distractors: ["物理学", "化学", "生物学"] },
    { word: "philosophy", phonetic: "/fəˈlɒsəfi/", meaning: "哲学", category: "subjects", distractors: ["心理学", "社会学", "政治学"] },
    { word: "physics", phonetic: "/ˈfɪzɪks/", meaning: "物理学", category: "subjects", distractors: ["化学", "生物学", "数学"] },
    { word: "politics", phonetic: "/ˈpɒlətɪks/", meaning: "政治学", category: "subjects", distractors: ["经济学", "社会学", "心理学"] },
    { word: "psychology", phonetic: "/saɪˈkɒlədʒi/", meaning: "心理学", category: "subjects", distractors: ["社会学", "哲学", "生物学"] },
    { word: "science", phonetic: "/ˈsaɪəns/", meaning: "科学", category: "subjects", distractors: ["艺术", "文学", "历史"] },
    { word: "statistics", phonetic: "/stəˈtɪstɪks/", meaning: "统计学", category: "subjects", distractors: ["数学", "经济学", "物理学"] },

    // ===== 旅游 Touring =====
    { word: "aquarium", phonetic: "/əˈkweəriəm/", meaning: "水族馆", category: "touring", distractors: ["动物园", "博物馆", "图书馆"] },
    { word: "culture", phonetic: "/ˈkʌltʃər/", meaning: "文化", category: "touring", distractors: ["自然", "科技", "工业"] },
    { word: "guest", phonetic: "/ɡest/", meaning: "客人", category: "touring", distractors: ["主人", "员工", "经理"] },
    { word: "hostel", phonetic: "/ˈhɒstl/", meaning: "旅社", category: "touring", distractors: ["酒店", "度假村", "别墅"] },
    { word: "picnic", phonetic: "/ˈpɪknɪk/", meaning: "野餐", category: "touring", distractors: ["宴会", "聚餐", "自助餐"] },
    { word: "reservation", phonetic: "/ˌrezəˈveɪʃn/", meaning: "预订", category: "touring", distractors: ["取消", "退订", "变更"] },
    { word: "souvenir", phonetic: "/ˌsuːvəˈnɪər/", meaning: "纪念品", category: "touring", distractors: ["日用品", "必需品", "消耗品"] },
    { word: "suite", phonetic: "/swiːt/", meaning: "套房", category: "touring", distractors: ["单间", "标间", "大床房"] },
    { word: "tourist", phonetic: "/ˈtʊərɪst/", meaning: "游客", category: "touring", distractors: ["居民", "员工", "商人"] },
    { word: "trip", phonetic: "/trɪp/", meaning: "旅行", category: "touring", distractors: ["工作", "学习", "休息"] },
    { word: "view", phonetic: "/vjuː/", meaning: "景色", category: "touring", distractors: ["室内", "地下", "隧道"] },

    // ===== 交通 Transportation =====
    { word: "aircraft", phonetic: "/ˈeəkrɑːft/", meaning: "飞机", category: "transportation", distractors: ["船", "火车", "汽车"] },
    { word: "airport", phonetic: "/ˈeəpɔːt/", meaning: "机场", category: "transportation", distractors: ["火车站", "汽车站", "港口"] },
    { word: "automobile", phonetic: "/ˈɔːtəməbiːl/", meaning: "汽车", category: "transportation", distractors: ["摩托车", "自行车", "三轮车"] },
    { word: "boat", phonetic: "/bəʊt/", meaning: "船", category: "transportation", distractors: ["飞机", "火车", "汽车"] },
    { word: "cabin", phonetic: "/ˈkæbɪn/", meaning: "舱", category: "transportation", distractors: ["甲板", "船头", "船尾"] },
    { word: "canoe", phonetic: "/kəˈnuː/", meaning: "独木舟", category: "transportation", distractors: ["游艇", "货轮", "渡船"] },
    { word: "crew", phonetic: "/kruː/", meaning: "机组人员", category: "transportation", distractors: ["乘客", "游客", "顾客"] },
    { word: "ferry", phonetic: "/ˈferi/", meaning: "渡船", category: "transportation", distractors: ["游艇", "货轮", "帆船"] },
    { word: "helicopter", phonetic: "/ˈhelɪkɒptər/", meaning: "直升机", category: "transportation", distractors: ["客机", "战斗机", "滑翔机"] },
    { word: "kayak", phonetic: "/ˈkaɪæk/", meaning: "皮划艇", category: "transportation", distractors: ["游艇", "货轮", "渡船"] },
    { word: "liner", phonetic: "/ˈlaɪnər/", meaning: "班轮", category: "transportation", distractors: ["货轮", "渔船", "帆船"] },
    { word: "passenger", phonetic: "/ˈpæsɪndʒər/", meaning: "乘客", category: "transportation", distractors: ["司机", "机长", "船长"] },
    { word: "platform", phonetic: "/ˈplætfɔːm/", meaning: "站台", category: "transportation", distractors: ["车厢", "座位", "过道"] },
    { word: "sailboat", phonetic: "/ˈseɪlbəʊt/", meaning: "帆船", category: "transportation", distractors: ["游艇", "货轮", "渡船"] },
    { word: "shipment", phonetic: "/ˈʃɪpmənt/", meaning: "货运", category: "transportation", distractors: ["客运", "空运", "快递"] },

    // ===== 车辆 Vehicles =====
    { word: "cab", phonetic: "/kæb/", meaning: "出租车", category: "vehicles", distractors: ["公交车", "地铁", "火车"] },
    { word: "camper", phonetic: "/ˈkæmpər/", meaning: "房车", category: "vehicles", distractors: ["轿车", "卡车", "货车"] },
    { word: "caravan", phonetic: "/ˈkærəvæn/", meaning: "旅行车", category: "vehicles", distractors: ["轿车", "跑车", "越野车"] },
    { word: "coach", phonetic: "/kəʊtʃ/", meaning: "长途客车", category: "vehicles", distractors: ["公交车", "出租车", "火车"] },
    { word: "lorry", phonetic: "/ˈlɒri/", meaning: "卡车", category: "vehicles", distractors: ["轿车", "货车", "面包车"] },
    { word: "minibus", phonetic: "/ˈmɪnibʌs/", meaning: "小巴", category: "vehicles", distractors: ["大巴", "公交车", "出租车"] },
    { word: "subway", phonetic: "/ˈsʌbweɪ/", meaning: "地铁", category: "vehicles", distractors: ["公交车", "出租车", "火车"] },
    { word: "tanker", phonetic: "/ˈtæŋkər/", meaning: "油轮", category: "vehicles", distractors: ["货轮", "客轮", "渔船"] },
    { word: "taxi", phonetic: "/ˈtæksi/", meaning: "出租车", category: "vehicles", distractors: ["公交车", "地铁", "火车"] },
    { word: "tractor", phonetic: "/ˈtræktər/", meaning: "拖拉机", category: "vehicles", distractors: ["卡车", "轿车", "货车"] },
    { word: "tram", phonetic: "/træm/", meaning: "有轨电车", category: "vehicles", distractors: ["地铁", "公交车", "出租车"] },
    { word: "truck", phonetic: "/trʌk/", meaning: "卡车", category: "vehicles", distractors: ["轿车", "面包车", "跑车"] },
    { word: "underground", phonetic: "/ˈʌndəɡraʊnd/", meaning: "地铁", category: "vehicles", distractors: ["公交车", "出租车", "火车"] },
    { word: "van", phonetic: "/væn/", meaning: "厢式货车", category: "vehicles", distractors: ["轿车", "卡车", "跑车"] },

    // ===== 天气 Weather =====
    { word: "breeze", phonetic: "/briːz/", meaning: "微风", category: "weather", distractors: ["暴风", "台风", "龙卷风"] },
    { word: "cold", phonetic: "/kəʊld/", meaning: "寒冷的", category: "weather", distractors: ["温暖的", "炎热的", "凉爽的"] },
    { word: "cool", phonetic: "/kuːl/", meaning: "凉爽的", category: "weather", distractors: ["炎热的", "温暖的", "寒冷的"] },
    { word: "dry", phonetic: "/draɪ/", meaning: "干燥的", category: "weather", distractors: ["潮湿的", "多雨的", "湿润的"] },
    { word: "dusty", phonetic: "/ˈdʌsti/", meaning: "多尘的", category: "weather", distractors: ["清洁的", "干净的", "新鲜的"] },
    { word: "freezing", phonetic: "/ˈfriːzɪŋ/", meaning: "冰冻的", category: "weather", distractors: ["温暖的", "炎热的", "融化的"] },
    { word: "hot", phonetic: "/hɒt/", meaning: "炎热的", category: "weather", distractors: ["寒冷的", "凉爽的", "温暖的"] },
    { word: "humid", phonetic: "/ˈhjuːmɪd/", meaning: "潮湿的", category: "weather", distractors: ["干燥的", "清爽的", "凉爽的"] },
    { word: "moisture", phonetic: "/ˈmɔɪstʃər/", meaning: "湿气", category: "weather", distractors: ["干燥", "热浪", "寒流"] },
    { word: "sticky", phonetic: "/ˈstɪki/", meaning: "闷热的", category: "weather", distractors: ["凉爽的", "干燥的", "清新的"] },
    { word: "warm", phonetic: "/wɔːm/", meaning: "温暖的", category: "weather", distractors: ["寒冷的", "冰冷的", "凉的"] },
    { word: "wet", phonetic: "/wet/", meaning: "潮湿的", category: "weather", distractors: ["干燥的", "干的", "晴朗的"] },

    // ===== 运动 Sports =====
    { word: "athlete", phonetic: "/ˈæθliːt/", meaning: "运动员", category: "sports", distractors: ["教练", "裁判", "观众"] },
    { word: "badminton", phonetic: "/ˈbædmɪntən/", meaning: "羽毛球", category: "sports", distractors: ["网球", "乒乓球", "排球"] },
    { word: "baseball", phonetic: "/ˈbeɪsbɔːl/", meaning: "棒球", category: "sports", distractors: ["足球", "篮球", "网球"] },
    { word: "basketball", phonetic: "/ˈbɑːskɪtbɔːl/", meaning: "篮球", category: "sports", distractors: ["足球", "排球", "网球"] },
    { word: "championship", phonetic: "/ˈtʃæmpiənʃɪp/", meaning: "冠军赛", category: "sports", distractors: ["热身赛", "友谊赛", "表演赛"] },
    { word: "court", phonetic: "/kɔːt/", meaning: "球场", category: "sports", distractors: ["泳池", "跑道", "操场"] },
    { word: "cricket", phonetic: "/ˈkrɪkɪt/", meaning: "板球", category: "sports", distractors: ["棒球", "足球", "篮球"] },
    { word: "cycling", phonetic: "/ˈsaɪklɪŋ/", meaning: "骑自行车", category: "sports", distractors: ["跑步", "游泳", "跳高"] },
    { word: "gymnasium", phonetic: "/dʒɪmˈneɪziəm/", meaning: "体育馆", category: "sports", distractors: ["图书馆", "餐厅", "教室"] },
    { word: "hockey", phonetic: "/ˈhɒki/", meaning: "曲棍球", category: "sports", distractors: ["足球", "篮球", "网球"] },
    { word: "jogging", phonetic: "/ˈdʒɒɡɪŋ/", meaning: "慢跑", category: "sports", distractors: ["冲刺", "跳跃", "投掷"] },
    { word: "judo", phonetic: "/ˈdʒuːdəʊ/", meaning: "柔道", category: "sports", distractors: ["拳击", "摔跤", "跆拳道"] },
    { word: "pitch", phonetic: "/pɪtʃ/", meaning: "球场", category: "sports", distractors: ["球门", "看台", "更衣室"] },
    { word: "recreation", phonetic: "/ˌrekriˈeɪʃn/", meaning: "娱乐活动", category: "sports", distractors: ["工作", "学习", "劳动"] },
    { word: "rugby", phonetic: "/ˈrʌɡbi/", meaning: "橄榄球", category: "sports", distractors: ["足球", "篮球", "网球"] },
    { word: "soccer", phonetic: "/ˈsɒkər/", meaning: "足球", category: "sports", distractors: ["篮球", "排球", "网球"] },
    { word: "squash", phonetic: "/skwɒʃ/", meaning: "壁球", category: "sports", distractors: ["网球", "乒乓球", "羽毛球"] },
    { word: "stadium", phonetic: "/ˈsteɪdiəm/", meaning: "体育场", category: "sports", distractors: ["剧院", "电影院", "博物馆"] },
    { word: "surfing", phonetic: "/ˈsɜːfɪŋ/", meaning: "冲浪", category: "sports", distractors: ["滑雪", "滑冰", "滑板"] },
    { word: "swimming", phonetic: "/ˈswɪmɪŋ/", meaning: "游泳", category: "sports", distractors: ["跑步", "跳高", "投掷"] },
    { word: "team", phonetic: "/tiːm/", meaning: "队伍", category: "sports", distractors: ["个人", "单人", "独自"] },
    { word: "tennis", phonetic: "/ˈtenɪs/", meaning: "网球", category: "sports", distractors: ["羽毛球", "乒乓球", "排球"] },
    { word: "treadmill", phonetic: "/ˈtredmɪl/", meaning: "跑步机", category: "sports", distractors: ["哑铃", "杠铃", "拉力器"] },
    { word: "walking", phonetic: "/ˈwɔːkɪŋ/", meaning: "散步", category: "sports", distractors: ["跑步", "冲刺", "跳跃"] },

    // ===== 爱好 Hobbies =====
    { word: "archery", phonetic: "/ˈɑːtʃəri/", meaning: "射箭", category: "hobbies", distractors: ["射击", "投掷", "击剑"] },
    { word: "chess", phonetic: "/tʃes/", meaning: "国际象棋", category: "hobbies", distractors: ["围棋", "跳棋", "军棋"] },
    { word: "climbing", phonetic: "/ˈklaɪmɪŋ/", meaning: "攀岩", category: "hobbies", distractors: ["跑步", "游泳", "骑行"] },
    { word: "gardening", phonetic: "/ˈɡɑːdnɪŋ/", meaning: "园艺", category: "hobbies", distractors: ["烹饪", "缝纫", "绘画"] },
    { word: "golf", phonetic: "/ɡɒlf/", meaning: "高尔夫", category: "hobbies", distractors: ["网球", "台球", "保龄球"] },
    { word: "painting", phonetic: "/ˈpeɪntɪŋ/", meaning: "绘画", category: "hobbies", distractors: ["雕塑", "摄影", "书法"] },
    { word: "photography", phonetic: "/fəˈtɒɡrəfi/", meaning: "摄影", category: "hobbies", distractors: ["绘画", "雕塑", "设计"] },
    { word: "pottery", phonetic: "/ˈpɒtəri/", meaning: "陶艺", category: "hobbies", distractors: ["织布", "编织", "雕刻"] },
    { word: "skateboarding", phonetic: "/ˈskeɪtbɔːdɪŋ/", meaning: "滑板", category: "hobbies", distractors: ["滑冰", "滑雪", "冲浪"] },
    { word: "snorkeling", phonetic: "/ˈsnɔːkəlɪŋ/", meaning: "浮潜", category: "hobbies", distractors: ["深潜", "游泳", "冲浪"] }
];
