// 雅思词库 Part 21 - 通用中频词汇补全 (Mid Freq Line 288-289)
var vocabularyPart21 = [
    { word: "full-grown", phonetic: "/ˌfʊl ˈɡrəʊn/", meaning: "成年的；发育成熟的", category: "general", distractors: ["幼小的", "成长的", "衰老的"] },
    { word: "fur", phonetic: "/fɜː/", meaning: "毛皮", category: "general", distractors: ["皮肤", "鳞片", "羽毛"] },
    { word: "gate", phonetic: "/ɡeɪt/", meaning: "门；大门", category: "general", distractors: ["窗户", "墙壁", "栅栏"] },
    { word: "gill", phonetic: "/ɡɪl/", meaning: "鳃", category: "general", distractors: ["肺", "鳍", "鳞"] },
    { word: "grey", phonetic: "/ɡreɪ/", meaning: "灰色的", category: "general", distractors: ["白色的", "黑色的", "蓝色的"] },
    { word: "hang", phonetic: "/hæŋ/", meaning: "悬挂", category: "general", distractors: ["放置", "丢弃", "拿起"] },
    { word: "helpfully", phonetic: "/ˈhelpfəli/", meaning: "有帮助地", category: "general", distractors: ["有害地", "无用地", "冷漠地"] },
    { word: "herd", phonetic: "/hɜːd/", meaning: "兽群", category: "general", distractors: ["鸟群", "鱼群", "人群"] },
    { word: "mine", phonetic: "/maɪn/", meaning: "我的；矿山", category: "general", distractors: ["你的", "工厂", "农场"] },
    { word: "minute", phonetic: "/ˈmɪnɪt/", meaning: "分钟", category: "general", distractors: ["小时", "秒", "刻"] },
    { word: "mist", phonetic: "/mɪst/", meaning: "薄雾", category: "general", distractors: ["大雨", "暴雪", "狂风"] },
    { word: "money", phonetic: "/ˈmʌni/", meaning: "钱", category: "general", distractors: ["时间", "信用", "荣誉"] },
    { word: "mountain", phonetic: "/ˈmaʊntən/", meaning: "山", category: "general", distractors: ["平原", "海洋", "盆地"] },
    { word: "move", phonetic: "/muːv/", meaning: "移动", category: "general", distractors: ["停止", "静止", "固定"] },
    { word: "name", phonetic: "/neɪm/", meaning: "名字", category: "general", distractors: ["地址", "电话", "职业"] },
    { word: "nation", phonetic: "/ˈneɪʃn/", meaning: "国家", category: "general", distractors: ["地区", "城市", "家庭"] },
    { word: "nature", phonetic: "/ˈneɪtʃə/", meaning: "大自然", category: "general", distractors: ["社会", "城市", "工业"] },
    { word: "noise", phonetic: "/nɔɪz/", meaning: "噪音", category: "general", distractors: ["音乐", "安静", "低语"] },
    { word: "non-stop", phonetic: "/ˌnɒn ˈstɒp/", meaning: "不停的", category: "general", distractors: ["间歇的", "停止的", "缓慢的"] },
    { word: "north", phonetic: "/nɔːθ/", meaning: "北", category: "general", distractors: ["南", "东", "西"] },
    { word: "owner", phonetic: "/ˈəʊnə/", meaning: "拥有者", category: "general", distractors: ["租赁者", "偷窃者", "访客"] },
    { word: "peace", phonetic: "/piːs/", meaning: "和平", category: "general", distractors: ["战争", "冲突", "混乱"] },
    { word: "play", phonetic: "/pleɪ/", meaning: "玩；戏剧", category: "general", distractors: ["工作", "学习", "睡觉"] },
    { word: "pool", phonetic: "/puːl/", meaning: "水池", category: "general", distractors: ["大海", "沙漠", "高山"] },
    { word: "porter", phonetic: "/ˈpɔːtə/", meaning: "搬运工", category: "general", distractors: ["经理", "司机", "厨师"] },
    { word: "present", phonetic: "/ˈpreznt/", meaning: "礼物；现在的", category: "general", distractors: ["过去的", "将来的", "琐碎的"] },
    { word: "print", phonetic: "/prɪnt/", meaning: "印刷", category: "general", distractors: ["手写", "绘画", "擦除"] },
    { word: "prize", phonetic: "/praɪz/", meaning: "奖品", category: "general", distractors: ["惩罚", "罚款", "成本"] },
    { word: "product", phonetic: "/ˈprɒdʌkt/", meaning: "产品", category: "general", distractors: ["原材料", "废料", "服务"] },
    { word: "property", phonetic: "/ˈprɒpəti/", meaning: "财产；属性", category: "general", distractors: ["债务", "租金", "消耗"] },
    { word: "pull", phonetic: "/pʊl/", meaning: "拉", category: "general", distractors: ["推", "举", "放"] },
    { word: "push", phonetic: "/pʊʃ/", meaning: "推", category: "general", distractors: ["拉", "提", "按"] },
    { word: "placebo", phonetic: "/pləˈsiːbəʊ/", meaning: "安慰剂", category: "general", distractors: ["特效药", "毒药", "疫苗"] }
];
