// 雅思词库 Part 24 - 写作功能词汇 (Essay Writing)
var vocabularyPart24 = [
    { word: "firstly", phonetic: "/ˈfɜːstli/", meaning: "首先", category: "essay", distractors: ["其次", "最后", "此外"] },
    { word: "to begin with", phonetic: "/tu bɪˈɡɪn wɪð/", meaning: "首先", category: "essay", distractors: ["总之", "此外", "结果"] },
    { word: "first of all", phonetic: "/fɜːst əv ɔːl/", meaning: "首先", category: "essay", distractors: ["最后", "例如", "然而"] },
    { word: "secondly", phonetic: "/ˈsekəndli/", meaning: "其次", category: "essay", distractors: ["首先", "最后", "不仅"] },
    { word: "thirdly", phonetic: "/ˈθɜːdli/", meaning: "第三", category: "essay", distractors: ["其次", "最后", "所以"] },
    { word: "finally", phonetic: "/ˈfaɪnəli/", meaning: "最后", category: "essay", distractors: ["首先", "其次", "此外"] },
    { word: "lastly", phonetic: "/ˈlɑːstli/", meaning: "最后", category: "essay", distractors: ["首先", "此外", "然而"] },
    { word: "in addition", phonetic: "/ɪn əˈdɪʃn/", meaning: "此外", category: "essay", distractors: ["由于", "但是", "总之"] },
    { word: "besides", phonetic: "/bɪˈsaɪdz/", meaning: "此外", category: "essay", distractors: ["除了", "因为", "所以"] },
    { word: "moreover", phonetic: "/mɔːrˈəʊvə/", meaning: "而且", category: "essay", distractors: ["由于", "然而", "导致"] },
    { word: "furthermore", phonetic: "/ˌfɜːðəˈmɔː/", meaning: "此外", category: "essay", distractors: ["因此", "但是", "首先"] },
    { word: "actually", phonetic: "/ˈæktʃuəli/", meaning: "实际上", category: "essay", distractors: ["大概", "将来", "理论上"] },
    { word: "in fact", phonetic: "/ɪn fækt/", meaning: "事实上", category: "essay", distractors: ["可能", "据称", "据说"] },
    { word: "as a matter of fact", phonetic: "/əz ə ˈmætər əv fækt/", meaning: "事实上", category: "essay", distractors: ["虽然", "因此", "所以"] },
    { word: "anyhow", phonetic: "/ˈenihaʊ/", meaning: "不管怎样", category: "essay", distractors: ["因此", "因为", "所以"] },
    { word: "therefore", phonetic: "/ˈðeəfɔː/", meaning: "因此", category: "essay", distractors: ["但是", "因为", "其次"] },
    { word: "thus", phonetic: "/ðʌs/", meaning: "因此", category: "essay", distractors: ["然而", "虽然", "由于"] },
    { word: "consequently", phonetic: "/ˈkɒnsɪkwəntli/", meaning: "结果", category: "essay", distractors: ["原因", "首先", "此外"] },
    { word: "as a result", phonetic: "/əz ə rɪˈzʌlt/", meaning: "结果", category: "essay", distractors: ["原因", "由于", "然而"] },
    { word: "for this reason", phonetic: "/fə ðɪs ˈriːzn/", meaning: "由于这个原因", category: "essay", distractors: ["无论如何", "不仅如此", "总之"] },
    { word: "since", phonetic: "/sɪns/", meaning: "既然；由于", category: "essay", distractors: ["但是", "因此", "尽管"] },
    { word: "for", phonetic: "/fɔː/", meaning: "因为；为了", category: "essay", distractors: ["所以", "但是", "除非"] },
    { word: "because of", phonetic: "/bɪˈkɒz əv/", meaning: "因为", category: "essay", distractors: ["尽管", "除了", "此外"] },
    { word: "due to", phonetic: "/djuː tuː/", meaning: "由于", category: "essay", distractors: ["尽管", "除了", "虽然"] },
    { word: "owing to", phonetic: "/ˈəʊɪŋ tuː/", meaning: "由于", category: "essay", distractors: ["尽管", "即使", "虽然"] },
    { word: "thanks to", phonetic: "/θæŋks tuː/", meaning: "多亏了", category: "essay", distractors: ["因为", "但是", "由于"] },
    { word: "yet", phonetic: "/jet/", meaning: "然而", category: "essay", distractors: ["已经", "所以", "而且"] },
    { word: "nevertheless", phonetic: "/ˌnevəðəˈles/", meaning: "然而", category: "essay", distractors: ["此外", "因此", "所以"] },
    { word: "on the contrary", phonetic: "/ɒn ðə ˈkɒntrəri/", meaning: "正相反", category: "essay", distractors: ["同样地", "例如", "此外"] },
    { word: "in contrast", phonetic: "/ɪn ˈkɒntrɑːst/", meaning: "相比之下", category: "essay", distractors: ["同样地", "而且", "因此"] },
    { word: "on the other hand", phonetic: "/ɒn ðɪ ˈʌðə hænd/", meaning: "另一方面", category: "essay", distractors: ["首先", "总之", "因为"] },
    { word: "provided that", phonetic: "/prəˈvaɪdɪd ðæt/", meaning: "如果；前提是", category: "essay", distractors: ["虽然", "由于", "除非"] },
    { word: "unless", phonetic: "/ənˈles/", meaning: "除非", category: "essay", distractors: ["如果", "由于", "虽然"] },
    { word: "in case", phonetic: "/ɪn keɪs/", meaning: "以防", category: "essay", distractors: ["因为", "所以", "然而"] },
    { word: "as long as", phonetic: "/əz lɒŋ əz/", meaning: "只要", category: "essay", distractors: ["即使", "尽管", "直到"] },
    { word: "although", phonetic: "/ɔːlˈðəʊ/", meaning: "虽然", category: "essay", distractors: ["因为", "所以", "然而"] },
    { word: "even though", phonetic: "/ˈiːvn ðəʊ/", meaning: "即使", category: "essay", distractors: ["因为", "所以", "而且"] },
    { word: "even if", phonetic: "/ˈiːvn ɪf/", meaning: "即使", category: "essay", distractors: ["如果", "由于", "因此"] },
    { word: "despite", phonetic: "/dɪˈspaɪt/", meaning: "尽管", category: "essay", distractors: ["因为", "如果", "因此"] },
    { word: "in spite of", phonetic: "/ɪn spaɪt əv/", meaning: "尽管", category: "essay", distractors: ["因为", "虽然", "由于"] },
    { word: "for instance", phonetic: "/fər ˈɪnstəns/", meaning: "例如", category: "essay", distractors: ["总之", "其次", "此外"] },
    { word: "such as", phonetic: "/sʌtʃ əz/", meaning: "比如", category: "essay", distractors: ["总之", "但是", "因此"] },
    { word: "in other words", phonetic: "/ɪn ˈʌðə wɜːdz/", meaning: "换句话说", category: "essay", distractors: ["此外", "因此", "所以"] },
    { word: "that is to say", phonetic: "/ðæt ɪz tu seɪ/", meaning: "也就是说", category: "essay", distractors: ["此外", "总之", "由于"] },
    { word: "namely", phonetic: "/ˈneɪmli/", meaning: "即", category: "essay", distractors: ["例如", "但是", "所以"] },
    { word: "in conclusion", phonetic: "/ɪn kənˈkluːʒn/", meaning: "总之", category: "essay", distractors: ["首先", "其次", "此外"] },
    { word: "to sum up", phonetic: "/tu sʌm ʌp/", meaning: "概括地说", category: "essay", distractors: ["首先", "其次", "例如"] },
    { word: "in short", phonetic: "/ɪn ʃɔːt/", meaning: "简而言之", category: "essay", distractors: ["此外", "因为", "随后"] },
    { word: "in brief", phonetic: "/ɪn briːf/", meaning: "简言之", category: "essay", distractors: ["首先", "其次", "具体来说"] },
    { word: "on the whole", phonetic: "/ɒn ðə həʊl/", meaning: "总的来说", category: "essay", distractors: ["具体而言", "相反", "此外"] },
    { word: "all in all", phonetic: "/ɔːl ɪn ɔːl/", meaning: "总而言之", category: "essay", distractors: ["首先", "例如", "然而"] }
];
