// 雅思词库 Part 15 - 通用高频词汇补全 A-D
var vocabularyPart15 = [
    { word: "a.m", phonetic: "/ˌeɪ ˈem/", meaning: "上午", category: "general", distractors: ["下午", "中午", "晚上"] },
    { word: "accomplish", phonetic: "/əˈkʌmplɪʃ/", meaning: "完成", category: "general", distractors: ["失败", "放弃", "中止"] },
    { word: "add", phonetic: "/æd/", meaning: "增加", category: "general", distractors: ["减少", "分割", "去除"] },
    { word: "again", phonetic: "/əˈɡen/", meaning: "再次", category: "general", distractors: ["从不", "已经", "只有"] },
    { word: "age", phonetic: "/eɪdʒ/", meaning: "年龄", category: "general", distractors: ["身高", "体重", "性别"] },
    { word: "air-conditioning", phonetic: "/ˈeə kəndɪʃənɪŋ/", meaning: "空调", category: "general", distractors: ["暖气", "冰箱", "电视"] },
    { word: "airfield", phonetic: "/ˈeəfiːld/", meaning: "停机坪", category: "general", distractors: ["跑道", "车站", "港口"] },
    { word: "airtight", phonetic: "/ˈeətaɪt/", meaning: "不透气的", category: "general", distractors: ["通风的", "松散的", "潮湿的"] },
    { word: "allowing", phonetic: "/əˈlaʊɪŋ/", meaning: "允许", category: "general", distractors: ["禁止", "拒绝", "忽略"] },
    { word: "almost", phonetic: "/ˈɔːlməʊst/", meaning: "几乎", category: "general", distractors: ["完全", "绝对", "从未"] },
    { word: "although", phonetic: "/ɔːlˈðəʊ/", meaning: "虽然", category: "general", distractors: ["因为", "但是", "因此"] },
    { word: "always", phonetic: "/ˈɔːlweɪz/", meaning: "总是", category: "general", distractors: ["从不", "有时", "经常"] },
    { word: "and", phonetic: "/ənd/", meaning: "和", category: "general", distractors: ["或", "但", "非"] },
    { word: "anything", phonetic: "/ˈeniθɪŋ/", meaning: "任何事物", category: "general", distractors: ["某些事物", "没有事物", "每一事物"] },
    { word: "appease", phonetic: "/əˈpiːz/", meaning: "安抚", category: "general", distractors: ["激怒", "攻击", "惩罚"] },
    { word: "approximate", phonetic: "/əˈprɒksɪmət/", meaning: "大约", category: "general", distractors: ["精确", "错误", "固定"] },
    { word: "arsenic", phonetic: "/ˈɑːsnɪk/", meaning: "砒霜", category: "general", distractors: ["糖", "盐", "药"] },
    { word: "as", phonetic: "/əz/", meaning: "作为", category: "general", distractors: ["但是", "因此", "因为"] },
    { word: "ash", phonetic: "/æʃ/", meaning: "灰烬", category: "general", distractors: ["火焰", "烟雾", "木材"] },
    { word: "audit", phonetic: "/ˈɔːdɪt/", meaning: "审计", category: "general", distractors: ["消费", "投资", "损耗"] },
    { word: "average", phonetic: "/ˈævərɪdʒ/", meaning: "平均", category: "general", distractors: ["最高", "最低", "独特"] },
    { word: "bargain", phonetic: "/ˈbɑːɡən/", meaning: "讨价还价", category: "general", distractors: ["全价", "赠送", "拒绝"] },
    { word: "bit", phonetic: "/bɪt/", meaning: "一点儿", category: "general", distractors: ["大量", "全部", "完全"] },
    { word: "brotherhood", phonetic: "/ˈbrʌðəhʊd/", meaning: "手足情谊", category: "general", distractors: ["竞争", "仇恨", "疏远"] },
    { word: "cabin", phonetic: "/ˈkæbɪn/", meaning: "船舱", category: "general", distractors: ["走廊", "甲板", "机翼"] },
    { word: "calculator", phonetic: "/ˈkælkjuleɪtə/", meaning: "计算器", category: "general", distractors: ["收音机", "温度计", "手表"] },
    { word: "call", phonetic: "/kɔːl/", meaning: "呼叫", category: "general", distractors: ["静默", "挂断", "拒绝"] },
    { word: "capsule", phonetic: "/ˈkæpsjuːl/", meaning: "胶囊", category: "general", distractors: ["药水", "针剂", "药片"] },
    { word: "catalyst", phonetic: "/ˈkætəlɪst/", meaning: "催化剂", category: "general", distractors: ["抑制剂", "溶剂", "原料"] },
    { word: "colonel", phonetic: "/ˈkɜːnl/", meaning: "陆军上校", category: "general", distractors: ["士兵", "将军", "中尉"] },
    { word: "column", phonetic: "/ˈkɒləm/", meaning: "列；柱", category: "general", distractors: ["行", "块", "面"] },
    { word: "decision-making", phonetic: "/dɪˈsɪʒn meɪkɪŋ/", meaning: "决策", category: "general", distractors: ["执行", "犹豫", "旁观"] }
];
